---
permalink: san-host/task_mounting_solaris_host_luns_with_sun_volume_manager_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, solaris, host, lun, volume, manager 
summary: Solaris Volume Manager を搭載した Solaris ホスト LUN を ONTAP 7-Mode から clustered ONTAP に移行した場合、移行後に LUN をマウントする必要があります。 
---
= 移行後の Solaris Volume Manager を搭載した Solaris ホスト LUN のマウント
:icons: font
:imagesdir: ../media/


[role="lead"]
Solaris Volume Manager を搭載した Solaris ホスト LUN を ONTAP 7-Mode から clustered ONTAP に移行した場合、移行後に LUN をマウントする必要があります。

コピーベースの移行の場合は、 7-Mode Transition Tool （ 7MTT ）でストレージカットオーバー処理を完了したあとに以下の手順を実行します。

コピーフリーの移行の場合は、 7MTT でデータと設定のインポート処理が完了したあとに以下の手順を実行します。

.手順
. ホストを再スキャンして、新しい clustered ONTAP LUN を検出します。
+
.. FC ホストポート（ fc-fabric タイプ）を特定します： +`*#cfgadm_– l_*`
.. 最初の fc-fabric ポートの設定を解除します :+`*#cfgadm – c unconfigure _c1_*`
.. 2 番目の fc-fabric ポートの設定を解除します :+`*#cfgadm – c unconfigure _c2_*`
.. 他の fc-fabric ポートについても上記の手順を繰り返します。
.. ホストポートとその接続デバイスを確認します +`*#cfgadm_– al_*`
.. ドライバ +`*#devfsadm – CV*` を再ロードします
+
`*#devfsadm – i iSCSI*`



. clustered ONTAP LUN が検出されたことを確認します。
+
「 * sanlun lun show * 」と表示されます

+
** clustered ONTAP LUN の「 lun-pathname 」の値は、移行前の 7-Mode LUN の「 lun-pathname 」の値と同じになります。
** 「モード」列には、「 7 」ではなく「 C 」が表示されます。


+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_sru17_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_sru17_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. 同じディスクセット名を使用して ' ディスクセットを既存の Solaris Volume Manager 構成にインポートします
+
'*metaimport-s_set-name_*

+
[listing]
----
# metaimport -s svm
Drives in regular diskset including disk c0t60A98000383035356C2447384D39654Ad0:
  c0t60A98000383035356C2447384D39654Ad0
  c0t60A98000383035356C2447384D396548d0
More info:
  metaimport -r -v c0t60A98000383035356C2447384D39654Ad0

# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. ファイルシステムのチェックを実行します。
+
'*fsck -F ufs/dev/md/SVM/rdsk/d1*

+
[listing]
----
# fsck -F ufs /dev/md/svm/rdsk/d1
** /dev/md/svm/rdsk/d1
** Last Mounted on /d1
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3a - Check Connectivity
** Phase 3b - Verify Shadows/ACLs
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cylinder Groups
3 files, 1573649 used, 3568109 free (13 frags, 446012 blocks, 0.0% fragmentation)
----
. 「 mount 」コマンドを使用して、各デバイスを手動でマウントします。
+
[listing]
----
# /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d1  /d1
  # /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d2  /d2
----
. マウントポイントを確認します。
+
「 * df -ah * 」と入力します


