---
permalink: san-host/task_testing_transitioned_luns_and_esxi_host_applications_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, esxi, applications, cutover, phase, copy, based 
summary: 7-Mode Transition Tool \ （ 7MTT \ ） 2.2 以降および Data ONTAP 8.3.2 以降を使用して ESXi ホストを移行する場合は、カットオーバーフェーズの前に移行した clustered Data ONTAP LUN をテストして、ホストとアプリケーションをオンラインにできるかどうかを確認できます。ソースホストでは、テスト中もソースの 7-Mode LUN への I/O を引き続き実行できます。 
---
= カットオーバー前の移行した LUN と ESXi ホストアプリケーションのテスト コピーベースの移行のフェーズ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool （ 7MTT ） 2.2 以降および Data ONTAP 8.3.2 以降を使用して ESXi ホストを移行する場合は、カットオーバーフェーズの前に移行した clustered Data ONTAP LUN をテストして、ホストとアプリケーションをオンラインにできるかどうかを確認できます。ソースホストでは、テスト中もソースの 7-Mode LUN への I/O を引き続き実行できます。

* 新しいテスト用ホストを新しいテスト環境でプロビジョニングする必要があります。
+
IP / MAC または UUID の重複や競合を回避するために、テスト用ホストはプライベートネットワークで設定する必要があります。

* ローカルハードディスクからブートされたホストを移行する場合は、テスト用ホストの ESXi のバージョンとドライバをソースホストと同じにする必要があります。
* FC / FCoE ホストと新しい clustered Data ONTAP ノード間のゾーニングを完了しておく必要があります。
* ソースホストと新しい clustered Data ONTAP ホスト間にゾーニングが存在しないようにしてください。
+
移行した clustered Data ONTAP LUN をテストモード中にソースホストが認識できると、ソースホストのサービスが予期せず停止する可能性があります。

* SAN ブートホストを移行する場合は、ネットワークアダプタを無効にする必要があります。


テスト用ホストとソースホスト間のハードウェアパリティを維持し、テスト用ホストで以下の手順を実行する必要があります。

clustered Data ONTAP LUN は、テスト時には読み取り / 書き込みモードになります。テストが完了してカットオーバーフェーズの準備を行う段階で、読み取り専用モードに切り替わります。

.手順
. ベースラインデータコピーが完了したら、 7MTT ユーザインターフェイス（ UI ）で「 * Test Mode 」を選択します。
. 7MTT UI で、 * 構成の適用 * をクリックします。
. テスト用ホスト上の clustered Data ONTAP ノードをゾーニングします。
. clustered Data ONTAP ノードにログインし、テストフェーズで 7MTT によって作成された igroup に新しいテスト用ホストイニシエータを追加します。
. 「 C ： \Program Files\NetApp\Virtual Transition Tool\` 」に移動します。
. 7MTT がインストールされている Linux ホストから、 7-Mode と clustered Data ONTAP の LUN のマッピングファイルを生成します。
+
'*transition cbt export lunmap -p project-name -o _file_path_*

+
例：

+
*transition cbt export lunmap -p SanWorkLoad-o c:\Libraires/Documents/7-C-lun-mapping.csv *

. テスト用ホストをオンラインにします。
+
** xref:concept_reconfiguration_of_vmware_software_iscsi_initiator.adoc[VMware ソフトウェア iSCSI イニシエータを移行後に再設定します]
** xref:task_setting_up_esxi_hosts_configured_for_san_boot_after_transition.adoc[あとで SAN ブート用に設定した ESXi ホストをセットアップします 移行]


. 移行したすべての clustered Data ONTAP LUN が検出されたことを確認します。
. SAN ブート以外のホストを移行する場合は、 VM を再登録します。
+
xref:task_reregistering_vms_after_transition_on_non_san_boot_esxi_host_using_vsphere_client.adoc[ESXi ホスト移行後の VM の再登録]

. ESXi ホストに必要な移行後の手順を実行します。
+
xref:concept_post_transition_requirements_for_esxi_hosts.adoc[ESXi ホストでの移行後の要件]

. ホストとアプリケーションをオンラインにします。
. 必要に応じてテストを実行します。
. テスト用ホストをシャットダウンします。
. 7MTT UI で、 * テストの終了 * をクリックします。
+
新しい clustered Data ONTAP LUN が読み取り専用になり、ソースの 7-Mode LUN からデータが再同期されます。

. 移行完了後に同じソースを使用する場合は、 clustered Data ONTAP ノード上の igroup を編集して適切なイニシエータを追加します。
+
テスト用ホストを本番環境に昇格する場合、 igroup を編集する必要はありません。



テストが完了したら、 Data ONTAP 7-Mode を実行しているコントローラに接続されたソースホストをいつシャットダウンするかを決定します。「 * 移行の完了」をクリックすると、ソースの 7-Mode ボリュームと LUN がオフラインになり、移行した clustered Data ONTAP LUN が読み取り / 書き込み可能になります。

* 関連情報 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["コピーベースの移行"]
