---
permalink: san-host/task_preparing_rhel_luns_for_transition_using_the_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, phel, lun, mount, points, dmmp, alias, names, cli 
summary: DMMP デバイス名を使用するマウントポイントを移行する前に、 DMMP デバイス名をそれぞれのファイルシステム UUID 番号に置き換える必要があります。 
---
= DMMP エイリアス名を使用するマウントポイントを含む RHEL LUN を準備しています CLI を使用した移行の場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DMMP デバイス名を使用するマウントポイントを移行する前に、 DMMP デバイス名をそれぞれのファイルシステム UUID 番号に置き換える必要があります。

この手順環境コピーベースの移行とコピーフリーの移行の 2 つです。

.手順
. 移行する LUN の SCSI デバイス ID を特定して記録します。
+
「 * sanlun lun show * 」と表示されます

+
SCSI デバイス ID は、出力の filename 列に表示されます。

. 移行する LUN の DMMP デバイス名を特定して記録します。
+
'*multipath -ll _SCSI_DEVICE_ID_*' と入力します

+
次の例では、 DMMP デバイス名「 360a9800037534562572b453855496b41 」が DMMP デバイス名です。

+
[listing]
----
[root@IBMx3550M3-229-169 ~]# multipath -ll /dev/sdc
dmmp_fs_lun (360a9800037534562572b453855496b41) dm-3 NETAPP, LUN
[size=1.0G] [features=3 queue_if_no_path pg_init_retries 50] [hwhandler=0][rw]
\_ round-robin 0 [prio=2][active]
	\_ 9:0:0:1 sdc 8:32  [active][ready]
	\_ 9:0:0:1 sdg 8:96  [active][ready]
----
. DMMP デバイスに設定されているファイルシステムを特定します。
+
`*bkid|grep -i _ DMMP _ デバイス _ 名前 _*`

+
出力の type 値はファイルシステムを識別します。

+
次の例では ' ファイル・システムは ext3 です

+
[listing]
----
[root@ibmx3550-229-108 ~]#blkid | grep -i 3600a09804d532d79565d47617679658
/dev/mapper/3600a09804d532d79565d47617679658:
UUID="450b999a-4f51-4828-8139-29b20d2f8708" TYPE="ext3" SEC_TYPE="ext2"
----
. LUN の UUID 番号を特定します。
+
`*dumppe2fs_device_path_name_|grep UUID*`

. DMMP デバイスがマウントされているディレクトリを特定します。
+
「 * df -h * 」と入力します

+
次の例では、「 /mnt/DMMP _ext3 」は DMMP デバイスがマウントされているディレクトリです。

+
[listing]
----
[root@IBMx3550M3-229-169 ~]# df -h
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/dmmp_fs_lun
1008M 34M 924M 4% /mnt/dmnp_ext3
----
. 「 /etc/fstab 」ファイルで、 DMMP デバイスのマウントポイントが定義されていることを確認します。
+
*cat /etc/fstab*`

+
DMMP デバイス名とマウントディレクトリが出力に表示されます。

. /etc/fstab ファイルのバックアップを作成します
+
`*cp /etc/fstab /etc/fstab_pre_transition_bup_*`

. 「 /etc/fstab 」ファイルを編集して、 DMMP デバイス名をそれぞれのファイルシステム UUID 番号に置き換えます。

