---
permalink: san-host/task_testing_luns_with_mounts_using_dmmp_aliases_on_rhel_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, pints, dmmp, alias, name, rhel 
summary: 7-Mode Transition Tool \ （ 7MTT \ ） 2.2 以降および Data ONTAP 8.3.2 以降を使用して Red Hat Enterprise Linux \ （ RHEL \ ）ホストのコピーベースの移行を実行する場合は、カットオーバーフェーズの前にエイリアス名を使用するマウントポイントを含む移行済みの clustered Data ONTAP LUN をテストすることができます。ソースホストでは、テスト中もソースの 7-Mode LUN への I/O を引き続き実行できます。 
---
= DMMP エイリアス名を使用するマウントポイントを含む LUN のテスト コピーベースの移行のカットオーバーフェーズ前の RHEL ホスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool （ 7MTT ） 2.2 以降および Data ONTAP 8.3.2 以降を使用して Red Hat Enterprise Linux （ RHEL ）ホストのコピーベースの移行を実行する場合は、カットオーバーフェーズの前にエイリアス名を使用するマウントポイントを含む移行済みの clustered Data ONTAP LUN をテストすることができます。ソースホストでは、テスト中もソースの 7-Mode LUN への I/O を引き続き実行できます。

新しい clustered Data ONTAP LUN をテスト用ホストにマッピングして、 LUN を移行できる状態にしておく必要があります。

テスト用ホストとソースホスト間のハードウェアパリティを維持し、テスト用ホストで以下の手順を実行する必要があります。

clustered Data ONTAP LUN は、テスト時には読み取り / 書き込みモードになります。テストが完了してカットオーバーフェーズの準備を行う段階で、読み取り専用モードに切り替わります。

.手順
. ベースラインデータコピーが完了したら、 7MTT ユーザインターフェイス（ UI ）で「 * Test Mode 」を選択します。
. 7MTT UI で、 * 構成の適用 * をクリックします。
. clustered Data ONTAP LUN の新しい SCSI デバイス名を取得します。
+
「 * sanlun lun show * 」と表示されます

+
次の例では '/dev/sdl' は 'lun_DMMP raw LUN の SCSI デバイス名であり '/dev/sdk' はの SCSI デバイス名です

+
「 lun_DMMP _ raw _ alias 」 LUN ：

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay)     lun-pathname               filename
-----------------------------------------------------------------
vs_brb     /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb     /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. clustered Data ONTAP LUN 用に DMMP デバイスを設定します。
+
「 * マルチパス * 」

. clustered Data ONTAP LUN のデバイスハンドル ID を取得します。
+
*multipath -ll *

+
デバイスハンドル ID の例を次に示します。「 3600a09804d532d79565d47617679764d` 」

. ソース・ホスト上の /etc/multipath.conf ファイルにエイリアスが定義されているかどうかを確認します
. エイリアス設定をテスト用ホストの「 /etc/multipath.conf 」ファイルに手動でコピーしますが、 7-Mode デバイスハンドル ID は、対応する clustered Data ONTAP デバイスハンドル ID に置き換えてください。
. 「マルチパス」コマンドを使用して、 clustered Data ONTAP LUN 用に DMMP デバイスを設定します。
. DMMP エイリアスデバイスに作成されたファイルシステムを特定します。
+
`*blkid_DMMP _DEVICE_NAME_*`

. DMMP デバイスをマウントします。
+
'*mount*'

. 必要に応じてテストを実行します。
. テストが完了したら、テスト用ホストをシャットダウンします。
+
*shutdown-h-t0 now *`

. 7MTT UI で、 * テストの終了 * をクリックします。


clustered Data ONTAP LUN をソースホストに再マッピングする場合は、ソースホストをカットオーバーフェーズ用に準備する必要があります。clustered Data ONTAP LUN をテスト用ホストにマッピングしたままにする場合、テスト用ホストでこれ以上の手順を実行する必要はありません。

* 関連情報 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Inventory Assessment Workbook からの移行前の情報収集]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[マウントを含む LUN 移行時のカットオーバーフェーズの準備 Linux ホストで DMMP デバイス名を使用するポイントです]
