---
permalink: san-host/task_preparing_for_cutover_when_transitioning_solaris_host_data_luns_with_zfs_file_systems.html 
sidebar: sidebar 
keywords: cutover, ontap, san, host, transition, host, data, lun, nfs, file, system 
summary: ZFS ファイルシステムを搭載した Solaris ホストデータ LUN を Data ONTAP 7-Mode から clustered Data ONTAP に移行する場合は、カットオーバーフェーズを開始する前に特定の手順を実行する必要があります。 
---
= Solaris ホストデータ LUN 移行時のカットオーバーフェーズの準備 ZFS ファイルシステムでは
:icons: font
:imagesdir: ../media/


[role="lead"]
ZFS ファイルシステムを搭載した Solaris ホストデータ LUN を Data ONTAP 7-Mode から clustered Data ONTAP に移行する場合は、カットオーバーフェーズを開始する前に特定の手順を実行する必要があります。

FC 構成を使用している場合は、 clustered Data ONTAP ノードへのファブリック接続とゾーニングを確立する必要があります。

iSCSI 構成を使用している場合は、 clustered Data ONTAP ノードへの iSCSI セッションを検出して、ログインする必要があります。

コピーベースの移行の場合は、 7-Mode Transition Tool （ 7MTT ）でストレージカットオーバー処理を開始する前に以下の手順を実行します。

コピーフリーの移行の場合は、 7MTT で 7-Mode のエクスポートおよび停止処理を開始する前に以下の手順を実行します。

.手順
. すべてのマウントポイントで I/O を停止します。
. アプリケーションベンダーの推奨事項に従って、 LUN にアクセスしている各アプリケーションをシャットダウンします。
. zpool をエクスポートします。
+
'*zpool export_pool-name_*

+
[listing]
----
# zpool export n_pool
----
. zpool がエクスポートされたことを確認します。
+
** 次のコマンドを実行して、エクスポートした zpool が表示されることを確認します。 +`*zpool import*`
** エクスポートした zpool が表示されないようにします :+`*zpool list*`


+
[listing]
----
# zpool export n_pool

# zpool list
no pools available

# zpool import
  pool: n_pool
    id: 5049703405981005579
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_pool                                   ONLINE
          c0t60A98000383035356C2447384D396550d0  ONLINE
          c0t60A98000383035356C2447384D39654Ed0  ONLINE
----

