---
permalink: san-host/task_making_san_boot_lun_primary_boot_lun_for_hp_ux_qlogic_hbas_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, boot, lun, primary, hp, ux, logic, hbas 
summary: Data ONTAP 7-Mode の HP-UX ホストが SAN ブートであった場合は、 clustered Data ONTAP への移行後に SAN ブート LUN をプライマリブート LUN にする必要があります。 
---
= SAN ブート LUN を用のプライマリブート LUN にします 移行後の HP-UX QLogic HBA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data ONTAP 7-Mode の HP-UX ホストが SAN ブートであった場合は、 clustered Data ONTAP への移行後に SAN ブート LUN をプライマリブート LUN にする必要があります。

* データ移行が完了している必要があります。
* ブート LUN が clustered Data ONTAP ノードからホストにマッピングされている必要があります。


SAN ブートは、 BCH メニューを使用する HP 9000 システムおよび HP-UX ローダ（ EFI ）を使用する HP Integrity サーバ上の HP-UX 11.3x でサポートされます。

コピーベースの移行の場合は、 7-Mode Transition Tool でストレージカットオーバー処理を完了したあとに以下の手順を実行します。HP-UX ホストでは、コピーフリーの移行はサポートされていません。

.手順
. シェルプロンプトを開きます。
+
'*Ctrl B*'

. EFI シェルでブートします。
+
EFI シェルは HP Integrity システムでのみ使用できます。

. シリアルコンソールを使用して、サービスプロセッサ（ MP ）へのログインにアクセスします。
. コンソール・リスト「 CO 」にアクセスします
+
EFI Boot Manager メニューが開きます。

. EFI Boot Manager メニューから EFI シェルメニューオプションを選択し、 EFI シェル環境にアクセスします。
. QLogic ドライバ番号を特定します。
+
「 * ドライバ * 」

+
ドライバ番号は DRV 列にあります。

. 各ドライバに対応するコントローラ番号を特定します。
+
'*drvcfg_driver_number_*

+
次の例では '27' はドライバ 23` に対応するコントローラ番号で '26' はドライバ 24` に対応するコントローラ番号です

+
[listing]
----
Shell> drvcfg 23
Configurable Components
		Drv[23]		Ctrl[27]			Lang[eng]

Shell> drvcfg 24
Configurable Components
		Drv[24]		Ctrl[26]			Lang[eng]
----
. ドライバの BIOS を開きます。
+
'*drvcfg_drv_number ctrl_number_-s *

. *4 を選択するには '*4*' を入力しますEdit Boot Settings] を選択します。
. Edit Boot Settings （起動設定の編集）で、「 6 」と入力して *6 を選択します。EFI Variable EFIFCScanLevel* 。
. EFI Variable EFIFCScanLevel] の値を 0 から 1 に変更するには、「 * 1 」と入力します。
. *7 を選択するには '*7*' と入力しますEnable World Login* 』を選択します。
. ワールドログインを有効にするには '*y*' を入力します
. 前のメニューに移動するには '*0*' を入力します
. メインメニューで '*11*' と入力して変更を保存します
. 終了するには '*12*' を入力します
. シェルプロンプトで、デバイスを再スキャンします。
+
「 * reconnect -r * 」と入力します

. LUN を表示して、ブートするパスを取得します。
+
'*map-r *'

+
LUN パスは、 Device 列の下に表示されます。ブート可能な SAN ディスクがマッピング・テーブル・カラムの下に表示され ' 出力文字列に WWN と Part 1 が表示されます

. SAN ブート LUN の LUN パスを入力します。
+
LUN パスの例は fs0 です。

. EFI シェルを終了します。
+
*cd efi *`

. HPUX ディレクトリに移動します。
+
「 * cd hpux * 」と入力します

. 新しい clustered Data ONTAP の SAN ブート LUN をプライマリブート LUN にします。
+
*bcfg boot add 1 hpux .efi "HP-UX - プライマリ・ブート "*`

. SAN ブート LUN の EFI にエントリを作成して、 HBA BIOS を手動で更新します。
. 代替ブートパスを作成します。
+
*bcfg boot add 2 hpux .efi "HPUX alternate boot" *`

. 3 つ目のブートパスを作成します。
+
*bcfg boot add 2 hpux .efi "HPUX Third boot" *`

. 4 つ目のブートパスを作成します。
+
*bcfg boot add 2 hpux .efi "HPUX fourth boot"*`


