---
permalink: san-host/task_mounting_solaris_host_luns_with_zfs_file_systems_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, solaris, host, lun, zfs, file, system 
summary: ZFS ファイルシステムを搭載した Solaris ホスト LUN を Data ONTAP 7-Mode から clustered Data ONTAP に移行した場合、移行後に LUN をマウントする必要があります。 
---
= 移行後の ZFS ファイルシステムを搭載した Solaris ホスト LUN のマウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ZFS ファイルシステムを搭載した Solaris ホスト LUN を Data ONTAP 7-Mode から clustered Data ONTAP に移行した場合、移行後に LUN をマウントする必要があります。

コピーベースの移行の場合は、 7-Mode Transition Tool （ 7MTT ）でストレージカットオーバー処理を完了したあとに以下の手順を実行します。

コピーフリーの移行の場合は、 7MTT でデータと設定のインポート処理が完了したあとに以下の手順を実行します。

. ホストを再スキャンして、新しい clustered Data ONTAP LUN を検出します。
+
.. FC ホスト・ポート（ fc-fabric タイプ）を特定します +`*#cfgadm – l*`
.. 1 番目の fc-fabric ポートの設定を解除します :+`*#cfgadm – c c1c*`
.. 2 番目の fc-fabric ポートの設定を解除します :+`*#cfgadm – c unconfigure C2*`
.. 他の fc-fabric ポートについても上記の手順を繰り返します。
.. ホスト・ポートおよび接続されているデバイスに関する情報が正しいことを確認します +`*#cfgadm – al*`
.. ドライバ +`*#devfsadm – cv *`*#devfsadm – i iSCSI*` を再ロードします


. clustered Data ONTAP LUN が検出されたことを確認します。
+
「 * sanlun lun show * 」 ** clustered Data ONTAP LUN の「 lun-pathname 」の値は、移行前の 7-Mode LUN の「 lun-pathname 」の値と同じになります。** 「モード」列には、「 7 」ではなく「 C 」が表示されます。

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_sru17_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_sru17_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. インポート可能な zpool を確認します。
+
'*zpool import*

+
[listing]
----
# zpool import
  pool: n_vg
    id: 3605589027417030916
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_vg                                     ONLINE
          c0t600A098051763644575D445443304134d0  ONLINE
          c0t600A098051757A46382B445441763532d0  ONLINE
----
. プール名またはプール ID を使用して、移行に使用された zpool をインポートします。
+
** '*zpool import_pool-name_*
** '*zpool import_pool-id_*


+
[listing]
----
# zpool list
no pools available

# zpool import
  pool: n_pool
    id: 5049703405981005579
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_pool                                   ONLINE
          c0t60A98000383035356C2447384D396550d0  ONLINE
          c0t60A98000383035356C2447384D39654Ed0  ONLINE

# zpool import n_pool
----
+
[+]

+
[listing]
----
# zpool import 5049703405981005579

[59] 09:55:53 (root@sunx2-shu04) /tmp
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -
----
. 次のいずれかのコマンドを実行して、 zpool がオンラインかどうかを確認します。
+
** '*zpool status*
** '*zpool list*


+
[listing]
----
# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
+
[+]

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -
----
. 次のいずれかのコマンドを使用して、マウントポイントを確認します。
+
** '*zfs list *
** 「 * df – ah * 」と入力します


+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2

#df –ah
n_pool                  12G   160K   9.1G     1%    /n_pool
n_pool/pool1           4.0G   1.5G   2.5G    38%    /n_pool/pool1
n_pool/pool2           4.0G   1.2G   2.8G    30%    /n_pool/pool2
----

