---
permalink: copy-based/concept_transition_terminology.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, terminology 
summary: 7-Mode Transition Tool に関連する移行の用語を理解しておくと、移行プロセスを理解しやすくなります。 
---
= 移行に関する用語
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool に関連する移行の用語を理解しておくと、移行プロセスを理解しやすくなります。

* * 収集と評価 *
+
データと構成を ONTAP に移行する前に、ストレージシステム、ホスト、およびアプリケーションを含むストレージ環境に関する情報を収集する必要があります。その後、収集したシステムの機能を評価し、移行先として選択した ONTAP バージョンでそれらの機能がどのように動作するかを確認する必要があります。

* * 移行 *
+
7-Mode ボリュームから ONTAP にデータと構成を移行することを指します。マイグレーションは、 7-Mode コントローラを評価したあとに実行する必要があります。

* * プロジェクト *
+
7-Mode Transition Tool では、プロジェクトを使用して、一連のボリュームの移行を設定し、管理することができます。

+
移行プロジェクトには、スタンドアロン、プライマリ、セカンダリの 3 つのタイプがあります。

+
** * スタンドアロンプロジェクト *
+
このプロジェクト内のボリュームは、他のストレージシステムのボリュームと SnapMirror 関係にないか、あるいは SnapMirror 関係を維持せずに移行します。

** * 一次プロジェクト *
+
このプロジェクト内のボリュームは、 SnapMirror 関係のソースボリュームです。

** * 二次プロジェクト *
+
このプロジェクト内のボリュームは、 SnapMirror 関係のデスティネーションボリュームです。



* * プロジェクトグループ *
+
7-Mode Transition Tool では、プロジェクトグループは論理コンテナであり、これを使用して関連するマイグレーションプロジェクトを保持できます。Default_Group という名前のデフォルトグループがシステムに常に 1 つ存在します。

* * 移行ピア関係 *
+
移行ピア関係は、 SnapMirror が 7-Mode ストレージシステムとクラスタ内の SVM の間に関係を確立し、移行対象である 7-Mode ボリュームのデータを ONTAP ボリュームにコピーできるかどうかを決定する、許可メカニズムです。移行ピア関係は、クラスタ管理者のみが作成でき、クラスタから開始されます。

* * 移行データ保護関係 *
+
Transition Data Protection （ TDP ；移行データ保護）関係は、 7-Mode システムと ONTAP システムの間に確立される Volume SnapMirror 関係です。

+
移行データ保護は移行時にのみサポートされます。ONTAP ボリュームのデータを 7-Mode ボリュームに戻して再同期することはできないため、この関係は長時間保持しないようにしてください。


