---
permalink: copy-based/concept_guidelines_for_creating_a_data_copy_schedule.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, create, data, copy, schedule 
summary: 7-Mode Transition Tool では、アクティブなスケジュールをチェックするスケジューラが 5 分ごとに実行されます。データコピースケジュールをアクティブにするための要件を確認しておく必要があります。データコピースケジュールの各種パラメータを設定する際に次のベストプラクティスに従うと、 SnapMirror 転送を効率的に管理できます。 
---
= データコピースケジュールの作成に関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool では、アクティブなスケジュールをチェックするスケジューラが 5 分ごとに実行されます。データコピースケジュールをアクティブにするための要件を確認しておく必要があります。データコピースケジュールの各種パラメータを設定する際に次のベストプラクティスに従うと、 SnapMirror 転送を効率的に管理できます。



== データコピースケジュールをアクティブにするための要件

* 7-Mode Transition Tool サービスが実行中であることが必要です。
+
7-Mode Transition Tool サービスを再起動した場合は、クレデンシャルが追加されるまで SnapMirror 処理が実行されません。

* SnapMirror データコピー処理を実行するには、少なくとも 1 つのデータコピースケジュールが必要です。
+
特定の期間に該当するスケジュールがない場合、その期間は SnapMirror データコピー処理が実行されません。

* SnapMirror 関係が休止状態にある場合は、データコピー処理は実行されません。
* データコピースケジュールに従って差分転送を実行するには、 7-Mode とクラスタのシステム時間を同期する必要があります。
+
7-Mode のシステム時間がクラスタ時間より遅れている場合は、指定した頻度よりも頻繁に更新がスケジュールされます。7-Mode のシステム時間がクラスタ時間より進んでいる場合は、指定した頻度よりも更新間隔が長くなります。





== データコピー時のベストプラクティス

SnapMirror レプリケーションのパフォーマンスを高めるには、ソースシステムとデスティネーションシステムの CPU 利用率と使用可能メモリが最適であることが必要です。また、マイグレーション処理に関係のないネットワークトラフィックを最小限に抑えることで、ソースシステムとデスティネーションシステム間のスループットを最大化して、レイテンシを最小限に抑える必要があります。



== データ転送の優先度

データコピー処理をスケジュールする際には、ベースライン処理または再同期処理が差分転送より優先されます。

SnapMirror 転送を解除するためにデータコピー処理を中止すると、まず差分転送が中止され、次にベースライン処理または再同期処理が中止されます。

差分転送では、前回の更新からの経過時間に基づいて、ソースボリュームとの時間差が大きいボリュームが優先されます。
