---
permalink: copy-based/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, cifs, local, users, groups 
summary: CIFS ローカルユーザおよびローカルグループをマイグレートする場合の、移行処理の実行に関する考慮事項を理解しておく必要があります。 
---
= CIFS ローカルユーザおよびローカルグループの移行に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS ローカルユーザおよびローカルグループをマイグレートする場合の、移行処理の実行に関する考慮事項を理解しておく必要があります。

* デスティネーションクラスタが clustered Data ONTAP 8.2 を実行している場合は、ローカルユーザとローカルグループに CIFS データを提供している 7-Mode ボリュームは移行しないでください。
+
7-Mode Transition Tool では、ローカルユーザとローカルグループを clustered Data ONTAP 8.2 に移行することができません。

* ローカルユーザとローカルグループを使用する 7-Mode コントローラまたは vFiler ユニットから、 BUILTIN ではない CIFS ローカルユーザおよびローカルグループを使用する SVM に、 CIFS データを提供するボリュームを移行することはできません。
+
移行では、 SVM が BUILTIN CIFS ローカルユーザおよびローカルグループのみを使用している必要があります。

+
特定の 7-Mode コントローラまたは vFiler ユニットから特定の SVM にローカルユーザとローカルグループを移行する場合、最初の移行プロジェクトからローカルユーザとローカルグループが移行されます。同じ 7-Mode コントローラまたは vFiler ユニットから同じ SVM へのそれ以降のプロジェクトの移行では、ローカルユーザとローカルグループの移行は無視されますが、移行は成功します。7-Mode システムのローカルユーザの名前を、 SVM の CIFS サーバ名と同じにすることはできません。

* clustered Data ONTAP 8.2.1 以降でサポートされるローカルユーザとローカルグループの最大数を把握しておく必要があります。
* パスワードが指定されていない、あるいは 14 文字を超えるパスワードが指定されている 7-Mode システムのローカルユーザアカウントは、「 * cifsUser@1 」というパスワードで ONTAP ソフトウェアに移行されます。
+
移行完了後、 Windows システムからパスワード「 * cifsUser@1 * 」を使用してこれらのユーザにアクセスします。その後、 SVM で次のコマンドを使用して、この CIFS ローカルユーザのパスワードを手動で変更する必要があります。

+
「 * cifs users-and-groups local-user set-password - vserver_svm_name _ -user-name_user_name _ * 」に設定します。

* 7-Mode Transition Tool の IP アドレスにターゲットの ONTAP ソフトウェアから到達できない場合、事前確認フェーズの ONTAP ソフトウェアへの CIFS ローカルユーザおよびグループの移行が 7-Mode Transition Tool によってブロックされます。事前確認フェーズでこのエラーが発生した場合は、を使用します
+
`* network ping -node local-destination_ip_address _*`

+
7-Mode Transition Tool の IP アドレスがターゲットの ONTAP ソフトウェアから到達可能であることを確認するコマンド。7-Mode Transition Tool の IP アドレスなど、 7-Mode Transition Tool で使用する設定オプションを変更するには、「 \etc\conf\transition-tool.conf 」ファイルを編集します。

* ローカルユーザとローカルグループの移行先の SVM にはデータ LIF が必要です。
* ローカルグループの複数のメンバーのシステム識別子（ SID ）が 7-Mode システムの単一のドメインユーザまたはグループにマッピングされている場合、事前確認フェーズでローカルユーザとローカルグループが ONTAP に移行されるのは 7-Mode Transition Tool でブロックされます。
+
事前確認フェーズでこのエラーが発生した場合は、 7-Mode システム上の単一のドメインユーザまたはグループにマッピングされている余分な SID を手動で削除する必要があります。その後、ドメインユーザまたはグループに 1 つの SID のみがマッピングされた状態で事前確認処理を再実行する必要があります。

+
https://["トラブルシューティングのワークフロー： CIFS ：システムに接続されているデバイスが機能していません"]



* 関連情報 *

http://["SMB / CIFS の管理"]
