---
permalink: copy-based/concept_prerequisites_for_transitioning_cifs_configurations.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prerequisites, cifs, configurations 
summary: CIFS 構成が 7-Mode Transition Tool で移行されるのは、 7-Mode システムおよびクラスタが一定の前提条件を満たしている場合のみです。条件が 1 つでも満たされていないと、構成は移行されません。 
---
= CIFS 構成を移行するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS 構成が 7-Mode Transition Tool で移行されるのは、 7-Mode システムおよびクラスタが一定の前提条件を満たしている場合のみです。条件が 1 つでも満たされていないと、構成は移行されません。



== 7-Mode の前提条件

* CIFS ライセンスが追加されていること。
* MultiStore ライセンスが有効になっている場合は、移行対象のボリュームが属する vFiler ユニットで許可されるプロトコルの一覧に CIFS が追加されていること。
* CIFS がセットアップされて、移行時に実行されていること。
* CIFS の認証タイプが Active Directory （ AD ）またはワークグループであること。




== クラスタの前提条件

* CIFS ライセンスが追加されていること。
* SVM で許可されるプロトコルの一覧に CIFS が追加されていること。
* SVM 用に DNS が設定されていること。
* ONTAP の各バージョンでサポートされている CIFS 認証方式は次のとおりです。
+
** clustered Data ONTAP 8.2.x / 8.3.x ： AD 認証
** ONTAP 9.0 以降では、 AD 認証とワークグループ認証がサポートされます。


* ターゲット SVM で、次の表に示す認証が使用されていること。
+
|===
| 7-Mode の認証方式 | clustered Data ONTAP 8.2.x および 8.3.x の認証方式 | ONTAP 9.5 以前の認証方式 


 a| 
広告
 a| 
広告
 a| 
広告



 a| 
ワークグループ
 a| 
広告
 a| 
ワークグループまたは AD

|===
* 7-Mode の CIFS サーバとターゲット SVM の CIFS サーバの間で AD ドメインが一致しない場合、 CIFS 構成を 7-Mode から ONTAP へ移行可能。AD ドメイン名の不一致が検出されるとエラーが生成されますが、このエラーは無視できます。移行を続行するには、エラーを承認します。
* 構成の適用フェーズ（カットオーバー前）の前に、 CIFS サーバが手動で設定されていること。
+
SVM 上に CIFS サーバを作成するには、次の 2 つの方法があります。

+
|===
| 状況 | 実行する処理 


 a| 
CIFS サーバ ID をターゲットに転送するか、または保持します SVM
 a| 
** ソースの 7-Mode システムまたは vFiler ユニット内のすべてのボリュームを 1 つのプロジェクトで移行するように計画する必要があります。
+
これは、 7-Mode システムの元の CIFS サーバ ID は移行後に失われ、クライアントを処理できなくなるためです。1 つのプロジェクトで移行できる最大ボリューム数は 160 です。このため、 CIFS サーバ ID を保持するには、 7-Mode システムのボリューム数を 160 個以下にして、そのすべてのボリュームを 1 つのプロジェクトで移行する必要があります。

+
CIFS サーバを作成するには、次の 2 つのオプションがあります。

+
... ONTAP のすべてのバージョンに適用可能：
+
**** 「構成の適用」フェーズ（カットオーバー前）の前に、一時的な CIFS ID を使用して 7-Mode システムに CIFS サーバを再設定する必要があります。
+
これにより、元の CIFS サーバ ID を SVM に設定できるようになります。「構成の適用」フェーズ（カットオーバー前）処理の実行中、 CIFS サーバが、新しい一時 ID を使用して 7-Mode システムで実行されていることを確認します。この操作は、カットオーバー前処理の実行中に 7-Mode から CIFS 構成を読み取るために必要です。

**** ターゲット SVM に、元の 7-Mode CIFS ID を使用して CIFS サーバを設定する必要があります。
**** 上記の条件を満たしたら、カットオーバー前処理を実行できます。
+
その後、カットオーバー前処理に続けてストレージカットオーバーをすぐに実行して、 ONTAP ボリュームにクライアントがアクセスできるようにする必要があります。



... ONTAP リリース 9.0 から 9.5 に適用可能：
+
**** CIFS サーバ名（ CIFS サーバの NetBIOS 名）を変更するには、「 vserver cifs modify 」コマンドを使用します。
+
これにより、ターゲット SVM に一時 ID で CIFS サーバを作成し、構成の適用（カットオーバー前）処理を実行します。

**** 「構成の適用」フェーズが終了したら、ターゲットクラスタで「 vserver cifs modify 」コマンドを実行して、ターゲット SVM の CIFS ID を 7-Mode の CIFS ID に置き換えることができます。








 a| 
新しい ID を使用します
 a| 
** 「構成の適用」フェーズ（カットオーバー前）の前に、ターゲット SVM に新しい CIFS ID を使用して CIFS サーバを設定する必要があります。
** 「構成の適用」フェーズ（カットオーバー前）処理の実行中に、 CIFS サーバが 7-Mode システムで実行されていることを確認します。
+
この操作は、「構成の適用」フェーズ（カットオーバー前）の実行中に 7-Mode システムから CIFS 構成を読み取るために必要です。

+
上記の条件を満たしたら、カットオーバー前処理を実行できます。その後、 SVM 構成をテストし、ストレージカットオーバー処理の実行を計画できます。



|===


* 関連情報 *

xref:concept_considerations_for_local_users_and_groups_transition.adoc[CIFS ローカルユーザおよびローカルグループの移行に関する考慮事項]
