---
permalink: copy-based/concept_restrictions_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, restrictions 
summary: 一部の 7-Mode ボリュームと構成を移行する場合の制限事項を把握する必要があります。 
---
= 移行に関する制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一部の 7-Mode ボリュームと構成を移行する場合の制限事項を把握する必要があります。

* 同じプロジェクト内のすべてのボリュームのベースライン転送が完了するまで、同じプロジェクト内のボリュームをカットオーバーすることはできません。
* 7-Mode のソースとデスティネーションの両方が Data ONTAP 7.3.x または 8.0.x を実行している場合に、 7-Mode のプライマリボリュームとセカンダリボリュームを移行するには、 7-Mode のプライマリボリュームから 7-Mode のセカンダリボリュームへのデータ更新がないことを確認してから、 7-Mode のセカンダリボリュームの移行を開始する必要があります。
+
7-Mode のプライマリボリュームから 7-Mode のセカンダリボリュームへのデータ更新スケジュールが、 7-Mode のセカンダリボリュームから ONTAP のセカンダリボリュームへのスケジュールと競合していないことを確認する必要があります。

* 7-Mode システムまたはクラスタ上のアグリゲートを 32 ビット形式から 64 ビット形式にアップグレードしている間は、移行を開始しないでください。移行に失敗します。
* 7-Mode Transition Tool では、 qtree SnapMirror 関係のデスティネーションである qtree を含むボリュームは移行されません。
+
ボリュームを移行する前に、 qtree SnapMirror 関係を解除する必要があります。

* ファンアウト SnapMirror 関係（ 1 つのプライマリボリュームが異なるコントローラにある複数のセカンダリボリュームと SnapMirror 関係にある状態）を、 7-Mode Transition Tool の Web インターフェイスで移行することはできません。
+
ファンアウト構成の SnapMirror 関係を移行するには、 7-Mode Transition Tool の CLI を使用する必要があります。セカンダリボリュームごとに個別のプロジェクトを作成し、セカンダリプロジェクトの移行が完了してから、プライマリボリュームの移行を作成して実行する必要があります。

* 複数の vFiler ユニットまたは複数の 7-Mode コントローラから同じ SVM に同時にボリュームを移行することはできません。
+
ある vFiler ユニットまたは 7-Mode コントローラからのボリュームの移行が完了してから、別の vFiler ユニットまたは 7-Mode コントローラからボリュームの移行を開始する必要があります。

* 7-Mode Transition Tool では、 vFiler ユニットが単一のエンティティとして移行されません。
+
ただし、 vFiler ユニット内のすべてのボリュームをプロジェクトの対象として選択することで、すべてのボリュームを移行できます。

* 7-Mode Transition Tool では、 vFiler ユニットのルートボリュームがデフォルトの vFiler ユニットに属する qtree に基づいている場合、そのルートボリュームは移行されません。
* 7-Mode Transition Tool では、ボリュームとその qtree が別々の vFiler ユニットに属している場合、ボリュームは移行されません。
+
このようなボリュームを移行すると、 qtree にアクセスできなくなります。



上記の制限事項の一部については、事前確認処理で情報が表示されます。
