---
permalink: copy-based/concept_considerations_for_deduplication_and_compression.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, deduplication, compression 
summary: 圧縮を使用する場合は、ソースボリュームとデスティネーションボリュームが 64 ビットアグリゲートに属している必要があります。ソースボリュームでの圧縮と重複排除によるすべての削減効果は、ネットワーク経由での移行中も維持されます。移行後は、圧縮と重複排除のすべての属性とストレージ削減効果が、ソースボリュームからデスティネーションボリュームに継承されます。 
---
= 重複排除と圧縮に関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
圧縮を使用する場合は、ソースボリュームとデスティネーションボリュームが 64 ビットアグリゲートに属している必要があります。ソースボリュームでの圧縮と重複排除によるすべての削減効果は、ネットワーク経由での移行中も維持されます。移行後は、圧縮と重複排除のすべての属性とストレージ削減効果が、ソースボリュームからデスティネーションボリュームに継承されます。

重複排除と圧縮が適用されたデータを移行すると、次の理由から移行中のネットワーク帯域幅を削減できます。

* 共有ブロックは 1 回だけ転送されます。
* 転送中も圧縮が維持されます。
* 圧縮と重複排除が適用されてスペースが削減されたデータは転送サイズが小さくなるため、転送完了までの時間が短縮されます。


移行中は、ソースボリュームで既存のデータの圧縮や重複排除を開始しないでください。重複排除または圧縮が進行中の場合は、その処理が完了してから移行を開始する必要があります。そのため、重複排除や圧縮が適用されていないデータやその他の一時メタデータファイルは、ネットワーク経由でデスティネーションボリュームに送信されません。

ONTAP に新たに書き込まれるデータに重複排除と圧縮を適用するには、移行完了後に、重複排除と圧縮のスケジュールを有効にする必要があります。

Data ONTAP 8.1 以降の重複排除機能では、アグリゲートコピーに加え、ボリューム内の部分的に順序付けられたフィンガープリントデータベースも維持されます。そのため、デスティネーションシステムにはソースボリュームでのスペース削減が継承されるだけでなく、順序付けられたフィンガープリントデータベースのコピーも継承されます。移行後に新しいボリュームで初めてボリューム効率化が実行されると、アグリゲートのフィンガープリントデータベースがデスティネーションボリューム内のコピーから自動的に構築されます。そのため、ボリューム効率化処理にかかる時間は一度だけ長くなります。

ソース・ボリュームが '8.1 より前の 7-Mode Data ONTAP を実行している場合 ' スペース節約を最適化するには '-scan-old-data option パラメータを指定して volume efficiency start コマンドを実行する必要がありますマイグレーションが完了したら、重複排除のスケジュールがクラスタでの要件に合っていることを確認し、ボリューム効率化ポリシーへの切り替えを検討する必要があります。
