---
permalink: copy-based/reference_ignorable_errors_during_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, ignorable, errors 
summary: 移行時に発生するエラーの一部は無視できます。移行を続行する前に、これらのエラーを承認する必要があります。 
---
= 移行時に無視できるエラーです
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行時に発生するエラーの一部は無視できます。移行を続行する前に、これらのエラーを承認する必要があります。

7-Mode Transition Tool CLI を使用して、コピーベースの移行プロジェクトに無視できるエラーカテゴリを追加する場合は、エラーの影響を把握しておく必要があります。エラーを無視したあとで、移行処理を再実行する必要があります。この時点で、エラーは警告メッセージに変わり、エラーは「 acknowledged 」と表示されます。警告が表示されても移行は続行できます。

|===
| カテゴリ | 説明 


 a| 
「 acknowledge -no-ASCII-Filenames-in-source-volumes 」を参照してください
 a| 
このエラーを承認すると、 CoC 検証処理の対象として選択した SnapLock ボリュームに、名前に非 ASCII 文字を含むファイルが 1 つもないことが確認されたことになります。



 a| 
「 acknowledge-snaplock-co-volume-autocommit_period 」というメッセージが表示されます
 a| 
このエラーをプロジェクトに追加すると、 SnapLock の CoC 検証結果の格納先として設定された ONTAP SnapLock ボリュームに自動コミット期間プロパティが設定されていても、 7- Mode Transition Tool は移行を続行します。



 a| 
「 nfs-qtrees -exported 」と表示されます
 a| 
このエラーを承認する場合は、 Data ONTAP 7-Mode と ONTAP の qtree エクスポートルールの違いを理解しておく必要があります。また、 7-Mode Transition Tool によって NFS エクスポートルールが適用されたあとで手動で実行しなければならない手順についても理解しておく必要があります。 https://["7MTT Precheck 10111 - 7-Mode ボリュームの移行方法 qtree レベルのエクスポートを設定する"]



 a| 
「 ignore-cifs-ad-domain-mismatch 」
 a| 
このエラーを承認すると、 7-Mode システムの CIFS Active Directory （ AD ）ドメインがターゲット SVM の CIFS AD ドメインと異なる場合であっても、 7-Mode Transition Tool では CIFS 構成の移行が続行されます。7-Mode システムとターゲット SVM の CIFS AD ドメインが信頼できるドメインであることを確認する必要があります。信頼できない場合、ターゲット SVM への CIFS 構成の移行は失敗します。 https://["Active Directory ドメインがの場合の CIFS 構成の移行方法 7-Mode とターゲット SVM で CIFS サーバが異なります"]



 a| 
「 ignore-ping-check-from-ic-LIFs to -7mode`
 a| 
このエラーをプロジェクトに追加すると、ターゲットクラスタのクラスタ間 LIF から 7-Mode ストレージシステムへの ping の送信チェックが実行されません。https://["7MTT Copy-Based Transition - シナリオの処理方法 7-Mode のデータコピー IP アドレスにターゲットクラスタから到達できません インタークラスタ LIF"]



 a| 
「 ignore-secondary-snapmirror-source-check 」を指定します
 a| 
このエラーをプロジェクトに追加すると、プライマリ 7-Mode の必要な詳細がすべてセカンダリプロジェクトに追加されたかどうかがチェックされません。そのため、セカンダリプロジェクトの完了（カットオーバー）処理中に、プライマリ 7-Mode ボリュームとセカンダリクラスタボリュームの間に SnapMirror 関係が作成されない可能性があります。



 a| 
「 ignore-configurion-limits-check 」
 a| 
このオプションを使用して構成の制限（事前確認のエラー）を承認し、移行を続行できます。このエラーを承認すると、ストレージカットオーバーに 3~8 時間以上かかります。これには、エクスポート、停止、インポートの各処理（自動処理）の時間と、ディスクシェルフを新しいコントローラに接続するための時間が含まれます。 https://["Copy-Free Transition でのストレージカットオーバーの時間に関する考慮事項"]



 a| 
「 mount -snaplock-volumes - using -7mode-volume-name 」のように入力します
 a| 
このエラーをプロジェクトに追加すると、 7-Mode Transition Tool では、マウントパス「 /<7-Mode_volume-name>` 」で SnapLock ボリュームがマウントされます



 a| 
「 acknowledge-no-snaplock-audit-transition-to-MCC 」
 a| 
このエラーをプロジェクトに追加すると、ターゲットクラスタが MetroCluster 構成に含まれていても、 7-Mode Transition Tool は移行を続行します。

|===