---
permalink: copy-based/task_aborting_a_subproject.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, abort, project 
summary: コントローラやクラスタのパフォーマンスに影響が生じている場合などに、実行中のプロジェクトを中止することができます。実行中のプロジェクトはダッシュボードから中止できます。 
---
= プロジェクトを中止する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラやクラスタのパフォーマンスに影響が生じている場合などに、実行中のプロジェクトを中止することができます。実行中のプロジェクトはダッシュボードから中止できます。

SnapMirror 関係にあるボリュームを移行するプロジェクトを中止する場合は、事前に次の点を考慮する必要があります。

* 両方のプロジェクトが開始されている場合は、一方のプロジェクトを中止するともう一方のプロジェクトも中止されます。
+
たとえば、プライマリプロジェクトを中止すると、セカンダリプロジェクトも中止されます。

* 現在のプロジェクトの中止が失敗した場合、もう一方のプロジェクトは中止されません。
* アクティブなプロジェクトが 1 つだけ中止されると、もう一方のプロジェクトは開始できません。
* プライマリプロジェクトを中止しても、 7-Mode のプライマリボリュームから ONTAP のセカンダリボリュームへのコピー処理は中止されません。
+
7-Mode のプライマリボリュームから対応する ONTAP のプライマリボリュームへのコピー処理のみが中止されます。




NOTE: 7-Mode プロジェクトを中止した場合、そのプロジェクトは削除するしかありません。中止したプロジェクトを再開することはできません。

.手順
. ダッシュボードで、中止するプロジェクトを選択します。
. * 中止 * をクリックします。
. クラスタで、移行の一環として作成された ONTAP ボリュームを削除します。
. 7-Mode システムで、 ONTAP ボリュームとの SnapMirror 関係を解除します。
. Volume SnapMirror 関係を中止する場合は、次の作業を行う必要があります。
+
.. 7-Mode プライマリボリュームと ONTAP セカンダリボリュームの間の SnapMirror 関係を解除して削除します。
.. プライマリ 7-Mode システムで、 ONTAP セカンダリボリュームとの SnapMirror 関係を解除します。




http://["ONTAP 9 のコマンド"]

https://["Data ONTAP 8.2 コマンド：マニュアルページリファレンス Vol.1 』を参照してください"]
