---
permalink: copy-based/task_creating_a_transition_project.html 
sidebar: sidebar 
keywords: create, transition, project, ontap, copy, based, transition 
summary: 移行プロジェクトの作成では、 7-Mode ボリュームの選択と Storage Virtual Machine （ SVM ）へのマッピング、インターフェイスのマッピング、および SnapMirror 関係のデータコピースケジュールの作成を行います。 
---
= 移行プロジェクトの作成
:icons: font
:imagesdir: ../media/


[role="lead"]
移行プロジェクトの作成では、 7-Mode ボリュームの選択と Storage Virtual Machine （ SVM ）へのマッピング、インターフェイスのマッピング、および SnapMirror 関係のデータコピースケジュールの作成を行います。

必要な SVM をクラスタ上に作成しておきます。

プロジェクト内のすべてのボリュームが同じ SVM にマイグレートされます。ボリュームを別々の SVM にマイグレートする場合は、複数のプロジェクトを作成する必要があります。

ターゲットクラスタが Data ONTAP 8.3.1 以前を実行していて、 NAS ボリュームに対して読み取り / 書き込みモードでカットオーバー前処理を実行する場合は、 NAS ボリュームと SAN ボリュームで別々のプロジェクトを作成する必要があります。これは、カットオーバー前読み取り / 書き込みモードはプロジェクトに SAN ボリュームがあるとサポートされないためです。

プロジェクトに SnapLock Compliance ボリュームが含まれている場合に、非 SnapLock Compliance ボリュームに対して読み取り / 書き込みモードでカットオーバー前処理を実行するには、 SnapLock Compliance ボリュームと非 SnapLock Compliance ボリュームで別々のプロジェクトを作成する必要があります。これは、カットオーバー前読み取り / 書き込みモードはプロジェクトに SnapLock Compliance ボリュームがあるとサポートされないためです。

.手順
. ホームページから * Copy-Based Transition * 移行方法を選択し、 * 計画の開始 * をクリックします。
+
新しいプロジェクトに必要なコントローラとクラスタが追加されていない場合は、 [Enter Device Credentials] ペインに詳細を入力できます。

. 必要な Data ONTAP 7-Mode システムと ONTAP システムがすべてツールに追加されていることを確認し、 * Next * をクリックします。
+
ソースボリュームの選択ページが表示されます。

. 移行する 7-Mode ボリュームを選択します。
+
.. 7-Mode コントローラペインで、ボリュームを追加する 7-Mode コントローラまたは vFiler ユニットを選択します。
.. プロジェクトグループに含めるボリュームを追加します。
+
|===
| 移行対象 | 作業 


 a| 
スタンドアロンボリューム
 a| 
移行するボリュームに対して、 * スタンドアロンで移行 * を選択します。

この列で最初のボリュームを選択すると、スタンドアロンプロジェクトが作成されます。



 a| 
Volume SnapMirror 関係
 a| 
... すべてのプライマリボリュームに対して、「 * SnapMirror 関係に移行」を選択します。
+
2 つのプロジェクトが作成されます。 1 つはプライマリボリューム用のプライマリプロジェクト、もう 1 つはセカンダリプロジェクトです。

... * オプション： * セカンダリコントローラがプロジェクトに含まれていない場合は、 [ 追加のストレージシステムクレデンシャルが必要です ] ダイアログボックスにコントローラの詳細を入力します。


|===
+
ボリュームに LUN が 1 つでも含まれている場合、ボリュームタイプは SAN と表示されます。

+
ボリューム名に設定されたハイパーリンクをクリックすると、ボリューム内の qtree と LUN およびそれらの属性を表示するダイアログボックスが開きます。

+

TIP: 同じプロジェクトに含まれるボリュームはすべて同じ定義（スタンドアロン、プライマリ、またはセカンダリ）にすることがベストプラクティスです。たとえば、プロジェクトにスタンドアロンボリュームと SnapMirror 関係が混在した状態にするのではなく、すべてのボリュームをスタンドアロンにします。

.. プロジェクトに含めるすべてのボリュームを選択したら、「 * プロジェクトを作成して続行 * 」をクリックし、表示されたダイアログボックスでプロジェクト名とプロジェクトグループの詳細を入力し、「 * 保存 * 」をクリックしてプロジェクトを作成します。


. SnapMirror データコピーに使用する 7-Mode IP アドレスとマルチパス IP アドレスを選択します。
+
.. 7-Mode のデータコピー IP アドレスを入力します。
+
デフォルトでは、 7-Mode システムの管理 IP アドレスがあらかじめこのフィールドに入力されています。必要に応じて、この IP アドレスをデータコピー権限のある任意の有効な IPv4 アドレスに変更できます。

.. データ転送のロードバランシングに複数のパスを使用する場合は、 [IP Configuration] ペインに IP アドレスを入力し、 [Next] をクリックします。


. Select SVM ページで、ターゲットクラスタと SVM を選択し、次の手順を実行します。
+
.. [Select a Clustered Data ONTAP System] ドロップダウンリストでクラスタ名をクリックして、ターゲットクラスタを選択します。
+
SVM が Select SVM ペインにロードされます。

.. Select SVM ペインから、ボリュームを移行するターゲット SVM を選択します。
.. 「 * 次へ * 」をクリックします。


+
7-Mode ボリュームを ONTAP の MetroCluster 構成に移行する場合は、 SVM のサブタイプが「 sync-source 」であることが必要です。

+
+ clustered Data ONTAP 8.2 の SVM を選択すると、 7-Mode ストレージシステムでローカルユーザとローカルグループ、 CIFS 共有、または CIFS ファイルが設定されているかどうかを確認するダイアログボックスが表示されます。7-Mode Transition Tool では、ローカルユーザとローカルグループを clustered Data ONTAP 8.2 に移行することができません。ローカルユーザとローカルグループがある場合は、 ONTAP 8.2.1 以降のサポートされるリリースの SVM を選択してください。

. SVM 監査ログデスティネーションパスのダイアログボックスで、デスティネーション SVM へのパスを入力して、 7-Mode ストレージシステムからの監査構成の移行を有効にします。
+
このパスは、 ONTAP システムで監査ログを保存する際に使用されます。

. Map Volumes ページで、移行先のボリュームを選択して、各ソースボリュームを目的のアグリゲートにマッピングします。
+
.. Map Origin Volumes to Aggregates on Target ペインで、 7-Mode ボリュームをコピーするアグリゲートを選択します。
.. クラスタのターゲットボリュームの名前を変更するには、 * Target Volume * フィールドに別の名前を入力します。
.. 「 * 次へ * 」をクリックします。


+
プロジェクトに含まれるすべてのボリュームと qtree が NFS 要求のみを処理するように設定されている場合は、監査構成の移行が実行されないため、監査パスを指定する必要はありません（指定しても無視されます）。

. Network Configuration ペインで、 SVM 上に作成する必要がある LIF に関する情報を指定します。
+

NOTE: FC LIF と iSCSI LIF は移行できません。これらの LIF は SVM に手動で作成する必要があります。

+
|===
| 状況 | 作業 


 a| 
既存の 7-Mode IP アドレスを移行する
 a| 
.. Select 7-Mode LIF * をクリックします。
.. 必要な 7-Mode IP アドレスを選択し、ターゲットノードとターゲットポートの詳細を入力します。
.. [ 保存（ Save ） ] をクリックします。




 a| 
新しい LIF を作成
 a| 
.. Add New LIF * をクリックします。
.. 表示されるダイアログボックスで、新しい LIF の詳細を入力します。
.. [ 保存（ Save ） ] をクリックします。


|===
+
移行完了後にネットワーク接続を確保するには、 7-Mode IP アドレスを ONTAP 内の同様のネットワークトポロジに移行する必要があります。たとえば、 7-Mode IP アドレスが物理ポート上に設定されている場合は、それらの IP アドレスを ONTAP 内の適切な物理ポートに移行する必要があります。同様に、 VLAN ポートまたはインターフェイスグループ上に設定された IP アドレスは、 ONTAP 内の適切な VLAN ポートまたはインターフェイスグループに移行する必要があります。

. 必要なすべての IP アドレスを追加したら、「 * 次へ * 」をクリックします。
. Configure Schedule （スケジュールの設定）ページで、ベースライン転送と差分転送のデータコピースケジュール、 Volume SnapMirror の同時転送数、および移行の SnapMirror 転送のスロットル制限を設定します。
+
データコピースケジュールとスロットル制限を指定することで、 DR 処理とデータコピー処理を効率的に管理できます。複数のスケジュールを作成し、各プロジェクトに最大 7 つのスケジュールを設定できます。たとえば、平日用と週末用にカスタマイズしたスケジュールを作成できます。

+

NOTE: スケジュールはソース 7-Mode コントローラのタイムゾーンに基づいて実行されます。

+
.. Configure Schedule （スケジュールの設定）ペインで、 * Create Schedule （スケジュールの作成） * をクリックします。
.. Create Data Copy Schedule ダイアログボックスで、新しいスケジュールの名前を入力します。
.. Recurring Days ペインで、 * Daily * または * Select Days * を選択して、データコピー処理を実行する曜日を指定します。
.. Time Interval ペインで、データ転送の開始時間 * と時間 * を指定します。
.. [ 時間間隔 ] ペインで、増分転送に * 更新頻度 * を指定するか、 * 連続更新 * を選択します。
+
継続的な更新を有効にすると、 SnapMirror の同時転送数に応じて、 5 分以上の間隔で更新が開始されます。

.. Parameters for Transition Data Copy Operations （ based on Volume SnapMirror ）ペインで、 Volume SnapMirror 同時転送の最大数（実行時と数に対する実行可能な SnapMirror 転送の割合）とスロットル制限（プロジェクト内のすべてのボリュームの最大帯域幅）を指定します。
+

NOTE: フィールドにあらかじめ入力されているデフォルト値は推奨値です。デフォルト値を変更する場合は、 7-Mode の SnapMirror スケジュールを分析し、指定する値がこれらのスケジュールに影響しないようにしてください。

.. [ 作成（ Create ） ] をクリックします。
+
新しいスケジュールが Transition Schedule ペインに追加されます。

.. 必要なデータコピースケジュールをすべて追加したら、「 * 次へ * 」をクリックします。


. SnapLock ボリュームを移行する場合は、ボリュームに対する移行後の CoC 検証を計画します。
+
.. CoC 検証が必要なソース SnapLock ボリュームを選択します。
+
CoC 検証プロセスは、読み書き可能な 7-Mode SnapLock ボリュームでのみサポートされ、読み取り専用ボリュームではサポートされません。CoC 検証は、名前に ASCII 文字のみを含むファイルが格納されている SnapLock ボリュームでのみサポートされます。

.. CoC 検証処理で生成されるフィンガープリントデータを格納する ONTAP ボリュームの詳細を入力します。
+
指定した SVM 上の既存の ONTAP ボリュームを指定する必要があります。

.. 「 * 次へ * 」をクリックします。




* 関連情報 *

xref:concept_guidelines_for_creating_a_data_copy_schedule.adoc[データコピースケジュールの作成に関する考慮事項]

xref:task_creating_schedule_for_snapmirror_transfers.adoc[SnapMirror 転送のデータコピースケジュールを作成します]

xref:concept_managing_snapmirror_transfers_and_schedule.adoc[SnapMirror 転送およびスケジュールの管理]

xref:task_transitioning_volumes_by_excluding_a_subset_of_configurations.adoc[CLI を使用した 7-Mode 構成の移行のカスタマイズ]

xref:task_managing_logical_interfaces.adoc[論理インターフェイスを管理する]

xref:task_removing_volumes_from_a_project.adoc[プロジェクトからボリュームを削除する]
