---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: ベースライン転送のために、 7-Mode ボリュームから ONTAP ボリュームへのデータコピーを開始することができます。ベースライン転送は、プロジェクトで設定されているデータコピースケジュールがアクティブになると開始されます。ベースライン転送の完了後は、データコピースケジュールに基づいて定期的に ONTAP ボリュームが更新されます。 
---
= 移行プロジェクトのデータコピーを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ベースライン転送のために、 7-Mode ボリュームから ONTAP ボリュームへのデータコピーを開始することができます。ベースライン転送は、プロジェクトで設定されているデータコピースケジュールがアクティブになると開始されます。ベースライン転送の完了後は、データコピースケジュールに基づいて定期的に ONTAP ボリュームが更新されます。

* プロジェクトに対して事前確認を実行し、エラーをすべて解決しておく必要があります。
* データ転送用のソースシステムとデスティネーションシステムの間に、広帯域幅、低レイテンシの専用ネットワークを設定しておく必要があります。
+

NOTE: SnapMirror マルチパスを使用して、データ転送の負荷を 2 つのパスに分散させることができます。

* セッションに対してデータコピースケジュールを設定する必要があります。


既存の SVM に移行する場合は、この処理の実行中にボリュームが作成されます。新しい SVM に移行する場合は、この処理の実行中に SVM とそのボリュームが作成されます。

7-Mode ボリュームと ONTAP ボリュームの間に SnapMirror 関係が作成されます。

.手順
. データコピーを開始します。
+
`*transition start -p _project_name_*`

+
開始操作が失敗し ' データ・コピーが開始されていない場合は ' 問題を解決し ' もう一度 transition start コマンドを実行する必要があります

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
プロジェクトが copy-baseline 状態になります。ベースライン転送が完了すると、プロジェクトは copy-update 状態になります。


