---
permalink: copy-based/task_applying_7_mode_configurations.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, apply, 7, mode, configuration 
summary: ベースラインデータコピーが完了したら、 7-Mode システムのすべての構成（プロトコルとサービスの構成を含む）を ONTAP ボリュームにコピーして適用することができます。ターゲットクラスタで ONTAP 8.3.2 以降のサポートされるリリースのいずれかのバージョンが実行されている場合は、このフェーズで SAN 構成が移行されます。 
---
= 7-Mode 構成の適用
:icons: font
:imagesdir: ../media/


[role="lead"]
ベースラインデータコピーが完了したら、 7-Mode システムのすべての構成（プロトコルとサービスの構成を含む）を ONTAP ボリュームにコピーして適用することができます。ターゲットクラスタで ONTAP 8.3.2 以降のサポートされるリリースのいずれかのバージョンが実行されている場合は、このフェーズで SAN 構成が移行されます。

SAN ボリュームを移行する場合は、クラスタ内のすべてのノードに対して該当するプロトコル（ iSCSI または FC ）のデータ LIF を少なくとも 1 つ作成しておく必要があります。

* 構成は、構成の適用（カットオーバー前）フェーズで適用されます。このフェーズには 2 つのモード（カットオーバー前読み取り専用モードとカットオーバー前読み取り / 書き込みモード）があります。


プロジェクトに次の要素が含まれている場合、カットオーバー前読み取り / 書き込みモードはサポートされません。

* SAN ボリュームとターゲットクラスタで Data ONTAP 8.3.1 以前が実行されている。この場合、次の構成はカットオーバー前フェーズでは適用されず、カットオーバーフェーズで適用されます。
+
** SAN 構成
** Snapshot スケジュールの設定


* SnapLock Compliance ボリューム。
+
プロジェクトに SnapLock Compliance ボリュームが含まれている場合は、 Snapshot スケジュールの設定はカットオーバー前フェーズでは適用されず、カットオーバーフェーズで適用されます。

+
を参照してください xref:concept_considerations_for_transitioning_of_snaplock_compliance_volumes.adoc[SnapLock Compliance ボリュームの移行に関する考慮事項]。



.手順
. ダッシュボードでプロジェクトを選択します。
. 構成を適用します。
+
|===
| すべての構成を適用する場合のモード | 作業 


 a| 
読み取り専用モード
 a| 
[ 構成の適用 *] をクリックします。



 a| 
読み取り / 書き込みモード
 a| 
.. [ テストモード *] チェックボックスをオンにします。
.. [ 構成の適用 *] をクリックします。
+
ONTAP ボリュームが読み取り / 書き込み可能となり、構成とデータアクセス処理をテストできます。

.. 構成の適用（カットオーバー前）ダイアログボックスで、テストモードでの構成の適用 * を選択します。


|===
. SnapMirror データコピー処理数とスロットル制限を指定するには、 [ この処理の同時 SnapMirror 転送数とスロットル制限をカスタマイズする * ] チェックボックスを選択します。
+
.. 移行中に実行する SnapMirror 同時転送の最大数を入力します。
.. SnapMirror 転送に使用できる使用可能なストリームの割合を入力します。
+
デフォルトでは、実行可能な Volume SnapMirror 転送の 50% が使用されます。

.. スロットル制限を入力するか、 * 最大 * を選択して最大帯域幅を使用します。
+
デフォルトでは、構成の移行には最大スロットルが使用されます。



. 移行する UNIX ベースまたは Microsoft AD ベースの Kerberos サーバ構成の詳細を指定するには、 * Transition Kerberos Configuration * チェックボックスを選択します。
+

NOTE: このオプションは、ソース 7-Mode ストレージシステムで Kerberos が設定されている場合にのみ有効になります。

+
.. Kerberos サーバのホスト名、 IP アドレス、ユーザ名、パスワードなどの詳細を入力します。
+

NOTE: Kerberos 構成を移行する場合は、少なくとも 1 つの LIF をプロジェクトの一部として移行する必要があり、かつその LIF がホスト名に解決できることが必要です。



. [* Continue （続行） ] をクリックします
+
Operation Progress ダイアログボックスが表示され、設定のコピー処理が開始されます。

. 構成の移行が読み取り / 書き込みモードで実行される場合は、構成のテストと検証が完了したら、「 * テストを完了」をクリックします。
+
このモードはテスト目的でのみ使用してください。テストモードでマイグレートしたボリューム上のクラスタに書き込まれたデータは、すべて失われます。

+
SnapMirror 関係が再確立され、 ONTAP ボリュームが（その時点でのそのプロジェクトのアクティブスケジュールに基づいて）再同期されます。7-Mode に書き込まれたすべてのデータが、 ONTAP ボリュームと再同期されます。

+

NOTE: 再同期が成功するためには、 7-Mode ボリュームと clustered Data ONTAP ボリュームに共通の Snapshot コピーが存在する必要があります。共通の Snapshot コピーは手動で削除しないでください。削除すると再同期が失敗します。



7-Mode IP アドレスは動作したままとなります。Storage Virtual Machine （ SVM ）上で LIF が次のように設定されます。

* 既存の 7-Mode IP アドレスは管理状態が down で作成されます。
+
ストレージカットオーバーの実行中に、これらの IP アドレスが 7-Mode システムから削除され、対応する Storage Virtual Machine （ SVM ） LIF の管理状態が up になります。カットオーバー前読み取り / 書き込みモードを選択した場合は、別の LIF を使用して、クラスタにマイグレートするボリュームにアクセスする必要があります。

* 新しい IP アドレスは管理状態が up で作成されます。
+
カットオーバー前読み取り / 書き込みモードを選択した場合は、これらの LIF を使用して、クラスタにマイグレートするボリュームへのアクセスをテストできます。



* 関連情報 *

xref:task_managing_logical_interfaces.adoc[論理インターフェイスを管理する]

xref:concept_considerations_for_quotas.adoc[クォータに関する考慮事項]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/7MTT_v2.0%2F%2FTransitioned_Data_ONTAP_features["7MTT v2.0/Transitioned Data ONTAP の機能"]
