---
permalink: copy-based/task_starting_baseline_data_copy.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, baseline, copy 
summary: プロジェクトを作成し、事前確認処理が完了したら、 7-Mode ボリュームから ONTAP ボリュームへのデータコピーを開始します。ベースラインデータコピー処理は、プロジェクトごとに開始できます。データコピー中は、不要なシステムプロセスとネットワークアクティビティを停止する必要があります。 
---
= ベースラインデータコピーを開始しています
:icons: font
:imagesdir: ../media/


[role="lead"]
プロジェクトを作成し、事前確認処理が完了したら、 7-Mode ボリュームから ONTAP ボリュームへのデータコピーを開始します。ベースラインデータコピー処理は、プロジェクトごとに開始できます。データコピー中は、不要なシステムプロセスとネットワークアクティビティを停止する必要があります。

データコピースケジュールを少なくとも 1 つ作成しておく必要があります。

テストマイグレーションを実行することで、使用する環境でのベースライン転送の所要時間を見積もることができるほか、 Volume SnapMirror 転送のパフォーマンスを評価できます。パフォーマンスに影響する可能性がある要因の一部を次に示します。

* 移行データコピースケジュールに対してオプションが選択されました
+
このスケジュールでは、 SnapMirror 同時転送の最大数と転送に使用される最大帯域幅の両方が制御されます。

* でサポートされる Volume SnapMirror 同時転送の最大数 7-Mode ソースコントローラ
* ソースの 7-Mode コントローラとデスティネーションの ONTAP コントローラの間のネットワーク帯域幅
+
マイグレーション処理に関係のないネットワークトラフィックを最小限に抑えることで、ソースシステムとデスティネーションシステム間のスループットを最大化して、応答時間を最小限に抑える必要があります。

* ソースとデスティネーション両方のコントローラのパフォーマンス機能
+
ソースシステムとデスティネーションシステムの CPU 使用率と使用可能メモリが最適である必要があります。

* データ中に実行される 7-Mode Volume SnapMirror 転送数 コピー


.手順
. ダッシュボードで、ベースラインデータコピーを開始するプロジェクトを選択します。
. [ ベースラインの開始 ] をクリックします。
+
バックグラウンドで事前確認が再度実行され、エラーが検出されなければ、データコピースケジュールに基づいてベースライン転送が開始されます。処理の進捗状況ダイアログボックスには、ベースラインデータコピー中に実行された事前確認処理のステータスに関する情報が表示されます。

. 「 * Volumes * 」タブをクリックして、ベースライン転送のステータスと進行状況を表示します。
+
各ボリュームの SnapMirror の詳細を表示するには、 * View Transition Details * をクリックします。SnapMirror の同時転送数は、現在アクティブなスケジュールの入力内容に基づいています。アクティブなスケジュールは、ダッシュボードの Data Copy Schedule タブで追跡できます。

+
ベースラインデータコピー処理が完了したら、プロジェクト作成時に指定したスケジュールに基づいて、 SnapMirror 差分更新が開始されます。



* 関連情報 *

xref:task_creating_schedule_for_snapmirror_transfers.adoc[SnapMirror 転送のデータコピースケジュールを作成します]
