---
permalink: copy-based/task_running_precheck_on_a_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, run, prechecks 
summary: 移行セッションを作成したら、 transition precheck コマンドでセッションを検証して、 7-Mode 環境が移行可能かどうかを確認できます。7-Mode ストレージシステムと SVM の間で、機能やセキュリティ設定などの要素に互換性があるかどうかを確認できます。 
---
= 事前確認を実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行セッションを作成したら、「 transition precheck 」コマンドでセッションを検証して、 7-Mode 環境が移行可能かどうかを確認できます。7-Mode ストレージシステムと SVM の間で、機能やセキュリティ設定などの要素に互換性があるかどうかを確認できます。

移行セッションが準備状態にあることが必要です。

transition cbt precheck コマンドは ' 詳細なエラー・メッセージ・レポートを生成しますレポートで特定された問題には、移行プロセスに問題が与える影響に応じて重大度レベルが割り当てられます。一部のエラーは移行を妨げる可能性があるため、エラーと警告に対しては対処策を実施する必要があります。また、移行処理に進む前に、他の重大度レベルのメッセージについてもその影響を確認する必要があります。

.手順
. 移行の互換性を確認します。
+
`*transition cbt precheck -p _project_name_*`

+
[listing]
----
7-Mode Transition Tool>transition cbt precheck -p project_finance

[1/14 ] Project status checks                                                  [    Errors     ]

Operation summary:
------------------
The 'precheck' operation on the project 'project_finance' has failed.

 1  Errors - Failed!

Do you want to see a detailed report {yes, no} [yes]:

1 Errors:
---------
90202: Checking whether any of the 7-Mode volumes are in 'offline' state.                              [     Error     ]
  > Following volumes are in 'offline' state.
  > CORRECTIVE-ACTION: Bring offline volumes online by using the following command: 'vol online
  > <volume_name>'.
  > AFFECTED-OBJECTS: { vol2 }

Next suggested steps:
---------------------
1. Review the 'precheck' operation results, fix all blocking errors and run the 'precheck' operation again.
2. Use the 'transition job-results -j 6e33e0a7-bb36-49df-91f3-2e52cbfa3074' command to see the results of this
operation.

Ran precheck for project 'project_finance'.
----


7-Mode ボリュームからのデータコピーを開始する前に、移行時に原因の問題が発生する可能性があるエラーをすべて解決する必要があります。
