---
permalink: copy-based/task_transitioning_volumes_by_excluding_a_subset_of_configurations.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, customize, cli 
summary: デフォルトでは、すべての 7-Mode 構成が ONTAP に移行されます。7-Mode Transition Tool CLI を使用して、ボリューム、 NFS 、 CIFS 、 SAN 、ネームサービスの構成の一部または全部を移行から除外することができます。また、 7-Mode の NFS エクスポートルールや Snapshot スケジュールを統合することや、既存の NFS エクスポートポリシーや Snapshot ポリシーをターゲット SVM で再利用することもできます。 
---
= CLI を使用した 7-Mode 構成の移行のカスタマイズ
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、すべての 7-Mode 構成が ONTAP に移行されます。7-Mode Transition Tool CLI を使用して、ボリューム、 NFS 、 CIFS 、 SAN 、ネームサービスの構成の一部または全部を移行から除外することができます。また、 7-Mode の NFS エクスポートルールや Snapshot スケジュールを統合することや、既存の NFS エクスポートポリシーや Snapshot ポリシーをターゲット SVM で再利用することもできます。

この作業は設定を適用する前に実行する必要があります。その後は変更はすべて無視されます。

7-Mode Transition Tool では、除外した構成の事前確認は実行されません。

デフォルトでは、すべての 7-Mode 構成が移行対象として選択されます。

最初にすべての構成の事前確認を実行してから、以降の事前確認の実行の際に 1 つ以上の構成を除外することを推奨します。これにより、移行対象から除外される構成とスキップされる事前確認を把握できます。

.手順
* 構成を除外して検証する
+
.. 構成を除外します： +`* transition cbt property-set-p_project_name_-n _config_property_name _-v true *`
+
`_config_property_name_` は除外する構成です

+
xref:reference_configurations_that_can_be_excluded.adoc[移行対象から除外可能な構成]

.. 構成を除外するために設定したプロパティの値を検証します。
+
`*transition cbt property-get-p_project_name>-n_config_property_name_*`



* 移行対象の NFS エクスポートルールを統合します。
+
** 7-Mode の類似する NFS エクスポートルールを統合して、 clustered Data ONTAP の単一のエクスポートポリシーにまとめます。これを移行後のボリュームまたは qtree に適用できます。 +`* transition cbt property-set -p project_name _-n nfs_consolidate-similiar-7mode-exports -v true *`
+
「 nfs-consolidate-similiar-7mode-exports 」プロパティを「 false 」に設定すると、 7-Mode の NFS エクスポートルールごとに新しい NFS エクスポートポリシーが ONTAP に作成されます。

** ツールによって作成されるエクスポートポリシーに一致する、 SVM 上の既存の NFS エクスポートポリシーを再利用します。これを移行後のボリュームまたは qtree に適用できます。 +`* transition cbt property-set -p project_name -n nfs_reuse-matching-svm-export-policies -v true *`


* 移行対象の Snapshot スケジュールを統合します。
+
** 同様の 7-Mode Snapshot スケジュールを統合して、 ONTAP の 1 つの Snapshot ポリシーにまとめます。これを移行後のボリュームに適用できます。 +`* transition cbt property-set -p project_name _-n consolidate-similar-7mode-snapshot-policies _ -v true *`
+
「 consolidate-similar-7mode-snapshot-policies 」プロパティを false に設定すると、 Snapshot スケジュールごとに新しい Snapshot ポリシーが ONTAP に作成されます。

** ツールによって作成される Snapshot ポリシーに一致する、 SVM 上の既存の Snapshot ポリシーを再利用します。これを移行後のボリュームに適用できます。 +`* transition cbt property-set -p project_name _-n reuse-matching-svm-snapshot-policies _ -v true *`



