---
permalink: copy-based/task_creating_schedule_for_snapmirror_transfers.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, create, data, copy, schedule, snapmirror, transfer 
summary: データコピースケジュールを作成して、プロジェクト内のボリュームの移行データコピー処理を効率的に管理することができます。また、 SnapMirror の同時転送数が上限に達してレプリケーション処理が失敗することがないように、このスケジュールの実行中に同時に実行する SnapMirror 転送の数も指定できます。 
---
= SnapMirror 転送のデータコピースケジュールを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データコピースケジュールを作成して、プロジェクト内のボリュームの移行データコピー処理を効率的に管理することができます。また、 SnapMirror の同時転送数が上限に達してレプリケーション処理が失敗することがないように、このスケジュールの実行中に同時に実行する SnapMirror 転送の数も指定できます。

* プロジェクトが、準備フェーズ、データコピーフェーズ、または構成の適用（カットオーバー前）フェーズであることが必要です。
* スケジュールが機能するためには、 7-Mode Transition Tool サービスが常時稼働している必要があります。



NOTE: データコピースケジュールは、 SnapMirror のベースラインコピー処理、更新処理、および再同期処理に使用されます。

* プロジェクトごとに少なくとも 1 つのデータコピースケジュールを作成する必要があります。
* プロジェクトごとに最大 7 つのスケジュールを作成できますが、 1 つのプロジェクト内でスケジュール同士が重なることはできません。
+
たとえば、営業時間内用と営業時間外用、 DR 時間内用と DR 時間外用、平日用と週末用にカスタマイズしたスケジュールを作成できます。

+

NOTE: 複数のプロジェクトで同じ 7-Mode コントローラまたはクラスタを使用している場合は、データコピースケジュールがプロジェクト間で重複しないようにしてください。

* 設定したスケジュールは、 7-Mode コントローラのタイムゾーンに基づいて適用されます。
* スケジュールの実行中に使用する SnapMirror の同時転送数は、 SnapMirror の同時ストリーム数に対する割合と、設定されている最大数に基づいて実行時に決定されます。
* スケジュールの実行中に使用する SnapMirror の同時転送数は、スケジュールで指定した SnapMirror 転送をツールが使用することによって既存の 7-Mode DR スケジュールが影響を受けないように指定する必要があります。
* ツールが使用している SnapMirror の同時転送数が、設定したスケジュール実行中の同時 SnapMirror 転送数よりも少ない場合は、新しい転送がスケジュールされて残りの転送数が使用されます。
* スケジュールが終わりに近づいている場合や、 7-Mode ストレージシステムで SnapMirror の同時転送数が削減された場合は、設定数の転送のみが使用されるようにするために余分な転送が中止されます。
+

NOTE: ベースラインコピーが進行中で、かつ Snapshot チェックポイントがまだ作成されていない場合は、 Snapshot チェックポイントが作成されるのを待ってから転送が中止されます。



.手順
. ダッシュボードの [ データのコピースケジュール ] ページで、 [ プロジェクトの編集 ] をクリックし、 [ スケジュールの構成 ] を選択してスケジュールを作成します。
. 新しいスケジュールの名前を入力します。
. Recurring Days ペインで、データコピー処理を実行する曜日を選択します。
+
|===
| データコピー処理を実行するタイミング | 作業 


 a| 
毎日
 a| 
「 * Daily * 」を選択します。これがデフォルト値です。



 a| 
特定の日のみ
 a| 
.. [ * 日の選択 * ] を選択します。
.. 曜日を選択します。


|===
. Time Interval ペインで、データコピースケジュールの開始時刻、期間、および頻度を指定します。
+
.. データコピー処理を開始する時間と分を * Start Time * ドロップダウン・リストから選択して、開始する時間を入力します。
+
有効な値は、 00 ： 00 から 23 ： 30 までです。

.. データコピー処理を実行する期間を入力し、期間（ * Duration * ）ドロップダウンリストから時間と分を選択します。
+

NOTE: スケジュールの実行時間は、 1 週間（ 167 時間 30 分）以内にします。

+
たとえば、「 20 ： 30 」と指定すると、開始時刻から 20 時間 30 分 SnapMirror 処理が実行されます。

.. ベースライン転送の完了後（設定したスケジュール実行時間内）に差分転送を実行する頻度を選択するには、次のいずれかの手順を実行します。
+
*** [ 頻度の更新 *] ドロップダウンリストから時間と分を選択します。
*** [ 継続的な更新 ] を選択します。
+
連続する更新間の最小遅延は 5 分です。





+
デフォルトでは 30 分ごとに SnapMirror 更新が実行されます。

. [Parameters for Transition Data Copy Operations] ペインで、 SnapMirror パラメータを入力します。
+
.. データコピーで使用する SnapMirror 同時転送の最大数を指定するには、次のいずれか、または両方を実行します。
+
*** データコピーに使用する Volume SnapMirror 転送の割合を指定します（スケジュールがアクティブな場合）。これには、 [* Maximum Number of Concurrent VSM Transfers * （同時 VSM 転送の最大数 * ） ] フィールドに割合を入力します。
+
実行可能な Volume SnapMirror 転送数は、実行時に計算されます。

+

NOTE: このペインには、プラットフォームでサポートされる SnapMirror 同時転送の最大数が表示されます。

*** このスケジュールの実行中に実行できる Volume SnapMirror 同時転送の最大数を * not conなら い * フィールドで指定します。両方の値を入力した場合は、小さい方の値が同時転送数として使用されます。




+
移行で使用される同時転送数は、スケジュールおよび設定されている同時転送数に基づいて実行時に計算されます。

+
+ 使用するプラットフォームがサポートする Volume SnapMirror 同時転送の最大数が 100 であり、現在実行できる転送数は 60 で、次の値を指定しているとします。

+
** 実行可能な Volume SnapMirror 転送数に対する割合は 50%
+
この割合に基づく同時転送の最大数は、 60 の 50% で 30 となります。

** Volume SnapMirror 同時転送の最大数は 25このシナリオでは、 Volume SnapMirror 同時転送の最大数は、この 2 つの値の少ない方である 25 に設定されます。
+
... 次のいずれかを実行して最大帯域幅を MB/s 単位で指定します（スロットル）。
+
|===
| 状況 | 作業 


 a| 
使用可能な帯域幅をすべて使用します
 a| 
「 * 最大 * 」を選択します。これがデフォルト値です。



 a| 
スロットル値を指定します
 a| 
[ * 次の値を超えない * ] フィールドに値を入力します。入力できる最大値は 4194303 です。

[+]

|===
+
スロットル値は、プロジェクト内のすべてのアクティブな転送間で均等に分配されます。

+

NOTE: 各転送のスロットルは、実行可能な Volume SnapMirror の同時転送数に基づいて実行時に決定されます。

+
アクティブなスケジュールに設定されているスロットル値が 200MB/s 、実行可能な同時転送数が 10 である場合は、それぞれの転送で 20MB/s の帯域幅が使用されます。







スケジュールは、プロジェクトがデータコピーフェーズまたは構成の適用（カットオーバー前）フェーズのときにのみ実行されます。



== データコピースケジュールを計画する例

100 個の SnapMirror 同時転送と 75 個の DR 関係をサポートする 7-Mode コントローラがあるとします。業務上の要件として、 SnapMirror 処理を次のタイミングで実行する必要があります。

|===
| 日 | 時間 | 現在使用されている SnapMirror 転送数 


 a| 
月曜日から金曜日まで
 a| 
午前 9 時から午後 5 時までです
 a| 
実行可能な転送数の 50%



 a| 
月曜日から金曜日まで
 a| 
午後 11 時 30 分午前 2 時 30 分まで
 a| 
DR に 75 個の転送を使用



 a| 
月曜日から金曜日まで
 a| 
午前 2 時 30 分午前 9 時までおよび

午後 5 時午後 11 時 30 分まで
 a| 
実行可能な転送数の 25%



 a| 
土曜から月曜
 a| 
午前 2 時 30 分（土曜）から午前 9 時（月曜）まで
 a| 
実行可能な転送数の 10%

|===
次のデータコピースケジュールを作成して、移行のデータコピー処理を管理できます。

|===
| スケジュール | オプション | 価値 


 a| 
peak_hours
 a| 
日数範囲
 a| 
月曜日から金曜日まで



 a| 
開始時間
 a| 
09:30



 a| 
期間
 a| 
8 ： 00



 a| 
最大同時転送数の割合
 a| 
50



 a| 
同時転送の最大数
 a| 



 a| 
スロットル（ MBps ）
 a| 
100



 a| 
頻度を更新します
 a| 
0 ： 00



 a| 
dr_active
 a| 
日数範囲
 a| 
月曜日から金曜日まで



 a| 
開始時間
 a| 
23 時 30 分



 a| 
期間
 a| 
3 ： 00



 a| 
最大同時転送数の割合
 a| 



 a| 
同時転送の最大数
 a| 
25



 a| 
スロットル（ MBps ）
 a| 
200



 a| 
頻度を更新します
 a| 
0 ： 30



 a| 
non_peak_non_dr1
 a| 
日数範囲
 a| 
月曜日から金曜日まで



 a| 
開始時間
 a| 
17:00



 a| 
期間
 a| 
6 ： 30



 a| 
最大同時転送数の割合
 a| 
75



 a| 
同時転送の最大数
 a| 



 a| 
スロットル（ MBps ）
 a| 
300



 a| 
頻度を更新します
 a| 
1 ： 00



 a| 
NON_PEK_NON_DR2
 a| 
日数範囲
 a| 
月曜日から金曜日まで



 a| 
開始時間
 a| 
02:30



 a| 
期間
 a| 
6 ： 30



 a| 
最大同時転送数の割合
 a| 
75



 a| 
同時転送の最大数
 a| 



 a| 
スロットル（ MBps ）
 a| 
300



 a| 
頻度を更新します
 a| 
1 ： 00



 a| 
week_ends
 a| 
日数範囲
 a| 
土曜日



 a| 
開始時間
 a| 
02:30



 a| 
期間
 a| 
53 ： 30



 a| 
最大同時転送数の割合
 a| 
90



 a| 
同時転送の最大数
 a| 



 a| 
スロットル（ MBps ）
 a| 
500



 a| 
頻度を更新します
 a| 
2 ： 00

|===