---
permalink: copy-based/task_preparing_7_mode_system_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, 7, mode 
summary: 移行を開始する前に、 SnapMirror ライセンスの追加、 7-Mode システムがターゲットクラスタと通信できるようにする、 TLS を有効にするなど、 7-Mode システムで一定の作業を完了しておく必要があります。 
---
= 7-Mode システムでの移行の準備
:icons: font
:imagesdir: ../media/


[role="lead"]
移行を開始する前に、 SnapMirror ライセンスの追加、 7-Mode システムがターゲットクラスタと通信できるようにする、 TLS を有効にするなど、 7-Mode システムで一定の作業を完了しておく必要があります。

移行する 7-Mode ボリュームがすべてオンラインになっている必要があります。

.手順
. 7-Mode システムで、 SnapMirror ライセンスを追加して有効にします。
+
.. 7-Mode システムに SnapMirror ライセンスを追加します。
+
'*license add_license_code_*

+
`_license_code_ は購入したライセンス・コードです

.. SnapMirror 機能を有効にします :+`* options snapmirror.enable on *`


. 次のいずれかのオプションを実行して、 7-Mode システムとターゲットクラスタが相互に通信できるように設定します。
+
** 「 SnapMirro .access 」オプションを「 all 」に設定します。
** 「 snapvault.access 」オプションの値を、クラスタ上のすべてのクラスタ間 LIF の IP アドレスに設定します。
** 「 snapmirror.access 」オプションが「 legacy 」で、「 napmirror.checkip.enable` 」オプションが「 off 」の場合は、 SVM 名を「 /etc/snapmirror.allow 」ファイルに追加します。
** 「 snapmirror.access 」オプションが「 legacy 」で、「 napmirror.checkip.enable` 」オプションが「 on 」である場合は、クラスタ間 LIF の IP アドレスを「 /etc/snapmirror.allow 」ファイルに追加します。


. ストレージシステムで HTTPS が有効でない場合は、 HTTPS を有効にします。
+
*options httpd. admin.ssl.enable on *`

+
HTTPS はデフォルトでは有効になっています。

. 7-Mode ストレージシステムで TLS を有効にして、 7-Mode Transition Tool が 7-Mode システムと通信できるようにします。
+
.. ストレージシステムで SSL がまだ有効になっていない場合は、 SSL をセットアップして開始します。
+
*secureadmin setup ssl *`

+
デフォルトでは、ストレージシステムに対して SSL がセットアップされています。ストレージシステムに対して SSL がすでにセットアップされている場合は、続行するかどうかの確認を求められます。変更を行わない場合は、 SSL のセットアップを終了できます。

.. SSL を有効にします。
+
'*options ssl.enable on *

+
TLS 経由の通信を許可するには、このオプションを有効にする必要があります。

.. TLS を有効にします。
+
'*options tls.enable on *

.. 7-Mode システムで SSLv2 と SSLv3 を無効にします。
+
'*options ssl.v2.enable off*

+
'*options ssl.v3.enable off*



+
7-Mode Transition Tool は、 7-Mode ストレージシステムとの通信に TLS または SSL プロトコルを使用します。ストレージシステムで TLS が有効になっている場合は、 TLS プロトコルを使用してストレージシステムと通信します。ストレージシステムで TLS が無効になっていて SSLv3 が有効になっている場合は、 SSLv3 を使用してストレージシステムと通信します。

+
+ 重要：セキュリティ上の脆弱性を回避するため、 TLS を有効にして、 SSLv2 と SSLv3 を無効にすることを推奨します。

. 7-Mode システムの Data ONTAP のバージョンに応じて、次の手順を実行します。
+
.. すべてのインターフェイスで SnapMirror トラフィックを許可します。
+
*options interface.blocked.snapmirror"" *

.. Data ONTAP バージョン 7.3.7 、 8.0.3 、 8.1 のいずれかを実行していて、 7-Mode Transition Tool 用の管理 IP アドレスとして e0M インターフェイスの IP アドレスを使用している場合は、 e0M インターフェイス上のデータトラフィックを許可します。
+
'*options interface.blocked.mgmt_data_traffic off*



. I2P 、読み取り時の割り当て、 NVFAIL のいずれかのオプションをボリュームで設定している場合は、次の手順を実行します。
+
.. これらのオプションを無効にしても、他の処理に影響がないことを確認します。
.. オプションを無効にします。
+
「 * vol options vol_name no_i2p off * 」というメッセージが表示されます

+
「 * vol options vol_name read_realloc off * 」を参照してください

+
'*vol options vol_name nvfail off*




