---
permalink: copy-based/task_completing_a_transition_project.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, complete, project 
summary: 移行を完了するには、個々のプロジェクトを完了します。この処理はシステムの停止を伴うため、実行するタイミングを検討する必要があります。SnapMirror 関係にあるボリュームを移行する際には、プライマリプロジェクトの移行を実行する前にセカンダリプロジェクトが完了している必要があります。 
---
= 移行プロジェクトの完了
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行を完了するには、個々のプロジェクトを完了します。この処理はシステムの停止を伴うため、実行するタイミングを検討する必要があります。SnapMirror 関係にあるボリュームを移行する際には、プライマリプロジェクトの移行を実行する前にセカンダリプロジェクトが完了している必要があります。

ストレージカットオーバーは数分で完了します。データの再マウントに必要な時間は、クライアントによって異なります。ストレージカットオーバーのタイミングやシステム停止時間は、次の要因によって異なります。

* 最後の更新
+
データの最終更新は、前回の更新以降にソースデータで行われた変更量によって異なります。差分転送によって、カットオーバー時に転送しなければならないデータ量が最小限に抑えられます。

* クライアントの再接続
+
クラスタに接続するために各クライアントを更新する必要がある場合は、更新が必要なクライアントの数によってカットオーバー時間が決まります。



停止されるのは、マイグレート中のボリュームのみです。ソースの 7-Mode ストレージシステム全体をシャットダウンする必要はありません。ソースシステム上のマイグレート対象でないボリュームはオンラインのままであり、引き続きアクセス可能です。

. 移行ダッシュボードで、完了するプロジェクトを選択します。
. クライアントアクセスを手動で切断
. 「 * 移行完了 * 」をクリックします。
+
.. 移行後に 7-Mode ソースボリュームをオンラインのままにする場合は、移行後にソースボリュームをオフラインにする * チェックボックスをオフにします。
+
デフォルトでは、このオプションが選択され、ソースボリュームがオフラインになります。

.. CoC 検証の対象として SnapLock ボリュームを選択した場合は、 CoC 検証 * チェックボックスを選択して、移行後に SnapLock ボリュームをオンラインのままにしておく必要がある SnapLock 7-Mode ボリュームをオフラインにしないことを確認します。
.. ONTAP 9.3 以降のサポートされるリリースを実行しているクラスタ間で SnapMirror 関係の移行を選択した場合は、「 SnapMirror 関係のタイプを data_protection から extended_data_protection * に手動で変換する必要があることを確認しています」チェックボックスをオンにします。
.. SnapMirror データコピー処理の数とスロットル制限を指定するには、「この処理に対する SnapMirror 同時転送数とスロットル制限をカスタマイズ」チェックボックスを選択します。
.. [* Continue （続行） ] をクリックします


+
カットオーバー処理の結果が表示されます。



移行用に選択した 7-Mode の IP アドレスが 7-Mode ストレージシステムで設定解除され、カットオーバー前に作成された関連 LIF の管理状態が up になります。7-Mode ボリュームはオフラインになります。

クラスタで、 vserver check lif-multitenancy run コマンドを実行して、移行後の LIF を使用してネームサーバに到達できることを確認します。


NOTE: 新しい LIF を作成した場合は、すべてのプロジェクトが完了したあとに、新しい IP アドレスとポートを使用して、移行したボリュームのユーザとアプリケーションをドライブに再マッピングする必要があります。

ONTAP 9.3 以降のサポートされるリリースを実行しているクラスタ間の SnapMirror 関係の移行が完了したら、 SnapMirror 関係のタイプを DP から XDP に変換する必要があります。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html["データ保護"]

* 関連情報 *

xref:concept_guidelines_for_deciding_when_to_cutover.adoc[カットオーバーの実行タイミングを決定する際のガイドライン]
