---
permalink: copy-based/task_generating_fc_zone_plan.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, generate, fc, zone, plan 
summary: FC スイッチについては、移行のための環境評価レポートの一部として FC ゾーン計画を生成し、マイグレーション後にイニシエータホストとターゲットをグループ化するためのゾーンを設定する必要があります。 
---
= FC ゾーン計画の生成
:icons: font
:imagesdir: ../media/


[role="lead"]
FC スイッチについては、移行のための環境評価レポートの一部として FC ゾーン計画を生成し、マイグレーション後にイニシエータホストとターゲットをグループ化するためのゾーンを設定する必要があります。

* 7-Mode システム、ホスト、およびクラスタを同じスイッチに接続する必要があります。
+
xref:concept_supported_configurations_for_generating_an_fc_zone_plan.adoc[FC ゾーン計画の生成でサポートされる構成]

* 必要なターゲット SVM と FC LIF をクラスタ上に作成しておく必要があります。
* ターゲット SVM で作成される FC LIF には、 7-Mode の WWPN とは異なる WWPN が割り当てられます。そのため、 FCP 用に SAN を移行する場合は、 FC ゾーニングを実行してください。


.手順
. [ 収集と評価 ] セクションで、 [ システムの追加 ] をクリックします。
. [Add System] ウィンドウで、次のいずれかの操作を実行します。
+
** システムを 1 つ追加します。
+
... システムの FQDN または IP アドレスを入力します。
... 指定したシステムのユーザ名とパスワードを入力します。
... システムタイプを選択します。
+
**** Data ONTAP ストレージシステム
**** ホスト： Microsoft Windows 、 Red Hat Linux Enterprise 、 VMware ESXi
**** FC スイッチ： Cisco および Brocade




** 複数のシステムを追加するには、 * 参照 * をクリックし、複数のシステムの資格情報を含むテキストファイルを選択します。


. [ 追加（ Add ） ] をクリックします。
+
評価ステータスが Ready のシステムに対しては、移行のための環境評価を実行できます。

. FC ゾーン計画を含む、移行のための環境評価レポートを作成します。
+
.. 移行のための環境評価を実施する、必要な FC スイッチを含むシステムを選択します。
.. Create Transition Assessment Report （移行評価レポートの作成） * をクリックします。
.. ペアシステムと FC ゾーンプランナーのダイアログボックスで、 7-Mode システム（シングルコントローラまたは HA ペア）、クラスタに接続されているスイッチ、クラスタの SVM を選択します。
.. ペアシステムの FC ゾーニングをクリックします * 。
.. Create Transition Assessment Report ダイアログボックスで、ターゲットクラスタの Data ONTAP バージョンを選択します。
.. レポートのファイル名に付けるプレフィックスを指定します。
.. [ レポートの生成（ Generate Report ） ] をクリックする。




FC ゾーン・プランは '.zip ファイルとして生成されますこの計画には、 7-Mode システムの igroup 構成ごとに作成されたゾーンが含まれています。各ゾーンには、イニシエータの WWPN が 1 つと SVM ターゲットの WWPN が複数含まれています。

この FC ゾーン計画を使用してゾーンを設定し、クラスタからのデータアクセスを提供するためにイニシエータホストとターゲットをグループ化する必要があります。
