---
permalink: copy-based/task_preparing_cluster_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, cluster 
summary: 移行の前に、 HTTPS の許可、インタークラスタ LIF のセットアップ、ネットワーク接続の検証などを実行し、クラスタが移行の要件を満たしていることを確認する必要があります。 
---
= クラスタで移行準備をします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行の前に、 HTTPS の許可、インタークラスタ LIF のセットアップ、ネットワーク接続の検証などを実行し、クラスタが移行の要件を満たしていることを確認する必要があります。

* クラスタと SVM のセットアップが完了している必要があります。
+
https://["ソフトウェアのセットアップ"]

+
ターゲット SVM が SVM ディザスタリカバリ関係にないことを確認します。

* クラスタが正常に動作している必要があります。また、テイクオーバーモードになっているノードがある場合は移行できません。
* 移行したボリュームを格納するターゲットアグリゲートには、 SFO ポリシーが設定されている必要があります。
* アグリゲートは、最大ボリューム制限に達していないノードに配置されている必要があります。
* 7-Mode システムの 32 ビットアグリゲートから Data ONTAP 8.2.x クラスタの 64 ビットアグリゲートへボリュームを移行する場合は、デスティネーションアグリゲートに 5% の追加スペースが必要です。
+
この追加スペースは、移行したボリュームを 64 ビット形式にアップグレードするために必要です。

+
https://["ディスクおよびアグリゲートの管理"]

* Volume SnapMirror 関係を移行するときに SVM ピア関係を確立するには、次の条件が満たされている必要があります。
+
** セカンダリクラスタに、プライマリ SVM と同じ名前の SVM が存在しない。
** プライマリクラスタに、セカンダリ SVM と同じ名前の SVM が存在しない。
** ソースの 7-Mode システムの名前が、ローカルの SVM や、すでにピア関係が設定されている SVM と重複していない。




移行中にクラスタを別のバージョンの ONTAP にアップグレードしないでください。


NOTE: 必要に応じて、クラスタを同じ ONTAP バージョンのパッチリリースにアップグレードすることができます。

.手順
. 管理ホストから、クラスタ管理 LIF を使用してクラスタにアクセスできることを確認します。
+
'*ssh_username@cluster_mgmt_ip_*

. クラスタで SSLv3 または FIPS を有効にします。
+
|===
| 有効にする項目 | 入力するコマンド 


 a| 
SSLv3
 a| 
*system services web modify -sslv3-enabled true *



 a| 
FIPS 140-2 準拠
 a| 
*system services web modify -ssl-fips-enabled true *

|===
+
FIPS 140-2 準拠を有効にすると、 SSLv3 は無効になります。ONTAP では、 FIPS 140-2 への準拠が有効な場合、 SSLv3 を有効にすることはできません。FIPS 140-2 を有効にしたあとで無効にしても、 SSLv3 は無効なままです。

+

IMPORTANT: SSLv3 にはセキュリティ上の脆弱性があるため、 FIPS を有効にすることを推奨します。

. クラスタ管理 LIF で HTTPS が許可されていることを確認します。
+
.. クラスタ管理 LIF のファイアウォールポリシーを表示します。
+
`* network interface show -vserver _svm_name -- lif_cluster_mgmt_lif__ -fields firewall-policy *`

+
[listing]
----
cluster1::> network interface show -vserver cluster1 -lif cluster_mgmt -fields firewall-policy
vserver lif          firewall-policy
------- ------------ ---------------
cluster1  cluster_mgmt mgmt
----
.. クラスタ管理 LIF に関連付けられているファイアウォールポリシーで HTTPS アクセスが許可されていることを確認します。
+
*system services firewall policy show -policy mgmt *

+
[listing]
----
cluster1::> system services firewall policy show -policy mgmt
Policy           Service    Action IP-List
---------------- ---------- ------ --------------------
mgmt
                 dns        allow  0.0.0.0/0, ::/0
                 http       allow  0.0.0.0/0, ::/0
                 https      allow  0.0.0.0/0, ::/0
                 ndmp       allow  0.0.0.0/0, ::/0
                 ntp        allow  0.0.0.0/0, ::/0
                 rsh        deny   0.0.0.0/0, ::/0
                 snmp       allow  0.0.0.0/0, ::/0
                 ssh        allow  0.0.0.0/0, ::/0
                 telnet     deny   0.0.0.0/0, ::/0
9 entries were displayed.
----


+
https://["システム管理"]

. クラスタの各ノードにインタークラスタ LIF を作成し、クラスタと 7-Mode システムが通信できるようにします。
+
.. 「 * network interface create -vserver _svm_name _ -lif _ intercluster_lif_ -role intercluster -home-node _home_node -home-port_port_IP_address _ip_address _netmask_netmask_ * ’を指定します
+
[listing]
----
cluster1::> network interface create -vserver cluster1-01 -lif intercluster_lif -role intercluster -home-node cluster1-01 -home-port e0c -address 192.0.2.130 -netmask 255.255.255.0
----
.. 静的ルートを作成します。
+
|===
| 移行先 | 実行するコマンド 


 a| 
ONTAP 9.5 以前または clustered Data ONTAP 8.3.x
 a| 
ネットワークルートが作成されます

[listing]
----
cluster1::> network route create -vserver vs0 -destination 0.0.0.0/0 -gateway 10.61.208.1
----


 a| 
clustered Data ONTAP 8.2.x の場合
 a| 
ネットワークルーティンググループルートの作成

[listing]
----
cluster1::> network routing-groups route create -vserver cluster1-01 -routing-group i192.0.0.0/18 -destination 0.0.0.0/0 - gateway 192.0.2.129
----
|===
.. インタークラスタ LIF から 7-Mode システムに ping を送信できることを確認します。
+
「 * network ping -lif lif_intercluster_lif _ -vserver_svm_name _ -destination_remote_InetAddress_* 」と入力します

+
[listing]
----
cluster1::> network ping -lif intercluster_lif -vserver cluster1 -destination system7mode
system7mode is alive
----
+
マルチパスの場合は、各ノードに 2 つのクラスタ間 LIF が必要です。

+
https://["ネットワークと LIF の管理"]




