---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: 7-Mode からの移行
    url: "/index.html"
  - title: リリースノート
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: 法的通知
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 新機能
      summary: 最新バージョンの 7-Mode の新機能を参照してください 移行ツール
      url: releasenotes.html
    - title: 7-Mode Transition Tool をインストールする
      summary: Microsoft Windows またはにツールをインストールする方法について説明します Linux の場合
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: 移行に必要なデータを収集
      summary: 移行に不可欠な情報を収集する方法をご確認ください
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: 7-Mode 管理者用のコマンドマップ
    links:
    - title: 7-Mode コマンドと ONTAP コマンドのマッピング
      summary: 7-Mode コマンドの ONTAP コマンドを探します
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: 7-Mode オプションと ONTAP コマンドのマッピング
      summary: 7-Mode オプションと ONTAP コマンドパラメータのマッピングを確認します
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: 7-Mode 構成ファイルと ONTAP コマンドのマッピング
      summary: 7-Mode 構成ファイルと ONTAP 構成コマンドのマッピングを作成する
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: 移行方法
    links:
    - title: コピーベースの移行
      summary: ツールを使用して、 7-Mode からコピーベースの移行を実行します を ONTAP に移動します
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: コピーフリーの移行
      summary: ツールを使用して、 7-Mode からコピーフリーの移行を実行します を ONTAP に移動します
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: SnapMirror を使用してデータを移行する
      summary: を使用して、 7-Mode から ONTAP にデータを移行する方法を理解します SnapMirror コマンド
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: SAN ホストの移行および修復
    links:
    - title: VMware ESXi
      summary: VMware ESXi ホストの移行前と移行後の要件を把握します
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux の場合
      summary: Red Hat Enterprise に対する移行前と移行後の要件を確認します Linux ホスト
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Windows の場合
      summary: Microsoft Windows ホストの移行前と移行後の手順を確認
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: すべてのONTAP 製品ドキュメント
