---
permalink: install-admin/concept_comparison_of_copy_free_transition_and_copy_based_transition.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, copy, free, transition, based 
summary: 7-Mode Transition Tool では、コピーベースの移行またはコピーフリーの移行を使用して、 7-Mode から ONTAP にデータと構成を移行できます。移行の前に、この 2 つの方法の違いを理解しておくことが重要です。 
---
= コピーフリーの移行とコピーベースの移行の比較
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool では、コピーベースの移行またはコピーフリーの移行を使用して、 7-Mode から ONTAP にデータと構成を移行できます。移行の前に、この 2 つの方法の違いを理解しておくことが重要です。

|===
| パラメータ | コピーフリーの移行 | コピーベースの移行 


 a| 
移行単位
 a| 
HA ペア
 a| 
ボリュームのグループ



 a| 
ハードウェア要件
 a| 
ディスクシェルフが再利用されます
 a| 
移行したボリュームを新しいディスクシェルフとディスクでホストします



 a| 
プラットフォーム要件
 a| 
ミッドレベルとハイレベルのプラットフォームでのみサポートされます https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]
 a| 
すべてのプラットフォームでサポートされます



 a| 
移行時間
 a| 
全体的に短い（データコピーは不要）
 a| 
長い（初回のベースラインと更新の転送時間は、ワークロード、ネットワーク帯域幅、移行するデータ容量によって異なります）



 a| 
データアクセスの中断
 a| 
時間の範囲内


IMPORTANT: ほとんどの場合、ストレージカットオーバーの所要時間は 3~8 時間です。カットオーバー時間には、エクスポートおよび停止処理とインポート処理の 2 つの自動処理をツールで実行するためにかかる時間と、ディスクシェルフを新しいコントローラに手動でケーブル接続するためにかかる時間が含まれます。エクスポートおよび停止処理とインポート処理の合計所要時間は、最大で 2 時間程度です。ディスクシェルフのケーブル接続には 1 時間から 6 時間かかる場合があります。

カットオーバー時間の目安には必要なテストの時間が含まれておらず、移行中にディスク障害などの予期しない障害が発生しないことを前提としています。
 a| 
分単位で指定します

|===