---
permalink: inventory-collect/task_collecting_inventory_and_generating_inventory_report.html 
sidebar: sidebar 
keywords: ontap, 7, mode, collect, inventory, generating, inventory, report, transition 
summary: Data ONTAP システム（ 7-Mode システムとクラスタのノード）、スイッチ、ホスト、およびホストアプリケーションに関する情報を収集できます。この情報を使用して、移行のための環境評価に使用する 7-Mode システム、ホスト、およびホストアプリケーションの詳細情報を含むインベントリレポートを生成できます。 
---
= インベントリの収集とインベントリレポートの生成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data ONTAP システム（ 7-Mode システムおよびクラスタのノード）、スイッチ、ホスト、およびホストアプリケーションに関する情報を収集できます。この情報を使用して、移行のための環境評価に使用する 7-Mode システム、ホスト、およびホストアプリケーションの詳細情報を含むインベントリレポートを生成できます。

* NetApp Support Site から「 tics.exe 」ファイルをダウンロードしておく必要があります。
* インベントリレポートを作成するストレージシステムとホストのユーザ名、パスワード、および IP アドレスが必要です。
* ストレージシステムおよびホストのユーザ名が、コマンドを実行するための十分な権限を持っている必要があります。
* インベントリ収集用に複数のシステムを追加する場合は、 ASCII 形式または UTF-8 形式でエンコードされたテキストファイルを作成し、システムの詳細（ 1 行に 1 つのシステム）を含める必要があります。
+
各システムの詳細は、次の形式で記述する必要があります。

+
'(ontap|windows|vmware|linux-cisco|brocade) ： // （ _domain_user_____\\_user__ ）： _[password]@] （ host_name|ip ） _'_

+
パスワードに「 * 」を指定すると、コマンドラインでパスワードの入力を求められます。

* すべての機能に関するインベントリ情報をワークブックに記録できるように、それらの機能を設定し、そのライセンスを有効にする必要があります。
* CIFS 共有名、ユーザ名、グループ名など、すべてのストレージシステム構成は UTF-8 形式である必要があります。
* FC ゾーン計画の場合は、 7-Mode システムとホストがスイッチに接続されている必要があります。
+
クラスタは、 7-Mode システムと同じスイッチに接続することも、同じファブリック内の新しいスイッチに接続することもできます。



Inventory Collect Tool では、最大 4 台のコントローラと 20 台のホストから同時に構成情報を収集できます。ただし、クォータ、 qtree 、エクスポート、または UNIX ユーザとグループを使用する拡張構成の場合は、インベントリレポートの生成に時間がかかることがあります。


NOTE: アクティブなストレージコントローラでのインベントリ収集処理は、ピーク時に実行しないでください。

. Windows のコマンドプロンプトで、 Inventory Collect Tool をダウンロードしたパスに移動します。
. システムの IP アドレスと資格情報を指定して 'tic' コマンドを実行し ' インベントリ・レポートを作成します
+
|===
| 情報を指定する方法 | 入力するコマンド 


 a| 
各システムで、コマンドラインインターフェイスを使用します
 a| 
'*ICT--cmd collect --output_filename_(ONTAP| Windows| VMware| Linux| Cisco| Brocade):/[(_user_|_domain _user_)[:(_password_|***)]@]_hostname_)...*

** `_filename_` は、インベントリレポートに指定する名前です。
** 「 ontap | windows | vmware|linux 」はシステムタイプです。
+
たとえば、 7-Mode ストレージシステムの場合のシステムタイプは ONTAP 、 Linux ホストの場合のシステムタイプは Linux です。

** 「 cisco|brocade 」は、サポートされている FC スイッチです。
** `_user|domain_user_` と `_password_ はシステム資格情報です。
+
コントローラにパスワードが設定されていない場合は ' パスワードとして文字を入力できます

** `_hostname_` はコントローラ、ホスト、またはスイッチの IP アドレスまたはホスト名です。




 a| 
テキストファイル内の複数のシステムの場合
 a| 
`*ICT -- cmd collect -- output_filename_--input_credentials_file.txt_*`

`_credentials_file.txt_` は、複数のシステムのシステム詳細と資格情報を含むテキストファイルです。

** ASCII 形式でエンコードされたテキストファイルのみがサポートされます。
** パスワードに「 * 」を指定すると、コマンドラインでパスワードの入力を求められます。
** コントローラにパスワードが設定されていない場合は、「」をパスワードとして入力できます。


|===
+

NOTE: ストレージ・システムで Windows 7 以降が実行されており ' インベントリ・レポートの出力 XML ファイルが保存されるフォルダへの権限に制限がある場合 ' 出力ファイルは自動的に VirtualStore ディレクトリに格納され ' アプリケーションは通常どおりに実行されます

+
ストレージシステムと Linux ホストのインベントリレポートが作成されます。生成されるレポートは 'collected_data.xml' および 'collected_data_InventoryWorkbook.xml' です

+
[listing]
----
ict --cmd collect --output collected_data ontap://root:test123@hostname1 linux://root@hostname2
----
+
インベントリ情報の収集に必要と推定時間がコントローラごとに表示されます。

+
インベントリワークブックとインベントリレポートが XML 形式で生成されます。

. Microsoft Office 2007 以降のバージョンを使用して、 Microsoft Excel でインベントリワークブックを表示する。


XML 形式のインベントリレポートを 7-Mode Transition Tool にインポートして 7-Mode コントローラとホストの機能を評価し、移行先として選択した clustered Data ONTAP バージョンでそれらの機能がどのように動作するかを確認できる状態になります。
