---
permalink: copy-free/concept_prerequisites_for_transitioning_cifs_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, cifs, configurations, prerequisites 
summary: CIFS 構成が 7-Mode Transition Tool で移行されるのは、 7-Mode システムおよびクラスタが一定の前提条件を満たしている場合のみです。条件が 1 つでも満たされていないと、構成は移行されません。 
---
= CIFS 構成を移行するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS 構成が 7-Mode Transition Tool で移行されるのは、 7-Mode システムおよびクラスタが一定の前提条件を満たしている場合のみです。条件が 1 つでも満たされていないと、構成は移行されません。



== 7-Mode の前提条件

* CIFS ライセンスが追加されていること。
* MultiStore ライセンスが有効になっている場合は、移行対象のボリュームが属する vFiler ユニットで許可されるプロトコルの一覧に CIFS が追加されていること。
* CIFS がセットアップされて、移行時に実行されていること。
+
クライアントアクセスの切断後、エクスポートフェーズを開始するための準備中であっても、 7-Mode システムで CIFS サービスが実行されている必要があります。

* CIFS の認証タイプが Active Directory （ AD ）またはワークグループであること。




== クラスタの前提条件

* CIFS ライセンスが追加されていること。
* ONTAP の各バージョンでサポートされている CIFS 認証方式は次のとおりです。
+
** clustered Data ONTAP 8.2.x / 8.3.x ： AD 認証
** ONTAP 9.0 以降では、 AD 認証とワークグループ認証がサポートされます。


* ターゲット SVM で、次の表に示す認証方式が使用されていること。
+
|===
| 7-Mode の認証方式 | clustered Data ONTAP 8.2.x および 8.3.x の認証方式 | ONTAP 9.5 以前の認証方式 


 a| 
広告
 a| 
広告
 a| 
広告



 a| 
ワークグループ
 a| 
広告
 a| 
ワークグループまたは AD

|===
* 7-Mode の CIFS サーバとターゲット SVM の CIFS サーバの間で AD ドメインが一致しない場合、 CIFS 構成を 7-Mode から ONTAP へ移行可能。
+
AD ドメイン名の不一致が検出されるとエラーが生成されますが、このエラーは無視できます。移行を続行するには、エラーを承認します。

* 構成の適用（カットオーバー前）フェーズの前に、 CIFS サーバが手動で設定されていること。
+
SVM 上に CIFS サーバを作成するには、次の 2 つの方法があります。

+
|===
| 状況 | 実行する処理 


 a| 
CIFS サーバ ID をターゲットに転送するか、または保持します SVM
 a| 
 You have the following two options to create the CIFS server:
.. ONTAP のすべてのバージョンに適用可能：
+
*** SVM のプロビジョニングフェーズの前に、一時的な CIFS ID を使用して、 7-Mode システムで CIFS サーバを再設定する必要があります。
+
これにより、元の CIFS サーバ ID を SVM に設定できるようになります。「 VM のプロビジョニング」フェーズと「エクスポートおよび停止」フェーズで、 CIFS サーバが、新しい一時 ID を使用して 7-Mode システムで実行されていることを確認する必要があります。この操作は、 SVM のプロビジョニングフェーズと「エクスポートおよび停止」フェーズで 7-Mode から CIFS 構成を読み取るために必要です。

*** ターゲット SVM に、元の 7-Mode CIFS ID を使用して CIFS サーバを設定する必要があります。
*** これらの条件を満たしたら、「 VM のプロビジョニング」操作を実行し、「エクスポートおよび停止」操作を実行して、 ONTAP ボリュームへのクライアントアクセスを有効にします。


.. ONTAP リリース 9.0 から 9.5 に適用可能：
+
*** CIFS サーバ名（ CIFS サーバの NetBIOS 名）を変更するには、「 vserver cifs modify 」コマンドを使用します。
+
この機能を使用する場合は、ターゲット SVM に一時 ID で CIFS サーバを作成してから、「 VM のプロビジョニング」処理を実行してください。

*** 「 import 」フェーズのあと、ターゲットクラスタで「 vserver cifs modify 」コマンドを実行して、ターゲット SVM の CIFS ID を 7-Mode の CIFS ID に置き換えることができます。






 a| 
新しい ID を使用します
 a| 
** 「 VM のプロビジョニング」フェーズの前に、ターゲット SVM に新しい CIFS ID を使用して CIFS サーバを設定する必要があります。
** 「 VM のプロビジョニング」フェーズと「エクスポートおよび停止」フェーズで、 CIFS サーバが 7-Mode システムで実行されていることを確認します。
+
この操作は、「 VM のプロビジョニング」および「エクスポートおよび停止」の実行中に 7-Mode から CIFS 構成を読み取るために必要です。

** これらの条件を確認したら、「 VM プロビジョニング」操作を実行できます。
+
その後、 SVM 構成をテストし、ストレージカットオーバーの実行を計画できます。



|===

