---
permalink: copy-free/concept_restrictions_during_preproduction_testing.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, preproduction, testing, restrictions 
summary: テスト時にはブロックされる処理、および推奨されない処理があります。これらの制限は、移行をコミットしない場合に 7-Mode へのロールバックを可能にするためにあります。 
---
= テスト時の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テスト時にはブロックされる処理、および推奨されない処理があります。これらの制限は、移行をコミットしない場合に 7-Mode へのロールバックを可能にするためにあります。



== ブロックされる処理

|===
| 操作 | 説明 


 a| 
アグリゲート Snapshot コピーを自動的に削除する（自動削除）
 a| 
エクスポート処理で作成された 7-Mode アグリゲートレベルの Snapshot コピーはロールバック時に必要なため、アグリゲートの使用スペースが増加しても Snapshot コピーは自動的には削除されません。


IMPORTANT: アグリゲートの空き物理スペースを監視して、テスト中にアグリゲートのスペースが不足しないようにする必要があります。



 a| 
別のアグリゲートへのボリュームの移動
 a| 
* 移行したアグリゲートにボリュームを移動することはできません。
* 移行したアグリゲートからクラスタ内のアグリゲートにボリュームを移動することはできます。




 a| 
ボリューム間での LUN のコピーまたは移動
 a| 
* 移行したボリュームに LUN をコピーまたは移動することはできません。
* 移行したボリュームからクラスタ内の他のボリュームに LUN をコピーまたは移動することはできます。




 a| 
アグリゲートを作成しています
 a| 
この処理は、ターゲットクラスタの HA ペアでは実行できません。クラスタ内の他のノードにはアグリゲートを作成できます。



 a| 
アグリゲートを削除しています
 a| 
エクスポート処理で作成された 7-Mode アグリゲートレベルの Snapshot コピーはロールバック時に必要なため、移行したアグリゲートを削除することはできません。



 a| 
移行したアグリゲートをルートアグリゲートとしてセットアップする
 a| 
移行したアグリゲートをルートアグリゲートとして選択することはできません。また、移行したアグリゲートの HA ポリシーを CFO に変更することはできません。



 a| 
ファイルコピー処理を実行しています
 a| 
* 移行したボリュームにファイルを移動またはコピー（単一ファイルのオンデマンドコピー）することはできません。
* 移行したボリュームからクラスタ内の他のボリュームにファイルを移動またはコピーすることはできます。




 a| 
既存のアグリゲートのミラーリング
 a| 
この処理はクラスタ内のすべてのアグリゲートでブロックされます。



 a| 
ターゲットの Data ONTAP バージョンをアップグレードまたはリバートする クラスタノード
 a| 
ターゲットクラスタノードをアップグレードまたはリバートする前に、プロジェクトをコミットする必要があります。



 a| 
ディスクを追加中です
 a| 
「 storage aggregate add-disks 」コマンドを admin 権限レベルで実行することはできません。ただし、 advanced 権限レベルでは実行できます。


IMPORTANT: 移行したアグリゲートのスペースを増やす場合、 7-Mode ディスクシェルフのスペアディスクだけを追加する必要があります。スペア・ディスクを追加するには '-disklist パラメータを使用します (`-diskcount ` パラメータは使用しないでください )



 a| 
移行したボリュームを SVM ルートボリュームとして指定
 a| 
移行したボリュームでは 'volume make-vsroot コマンドを実行できません

|===


== 推奨されない処理

|===
| 操作 | ロールバック前の対処方法 


 a| 
アグリゲートの再配置

移行したアグリゲートの所有権はその HA パートナーに切り替わります。
 a| 
7-Mode Transition Tool では、プロジェクトに保存されたターゲットノードのマッピング情報に基づいてアグリゲートが 7-Mode コントローラにマッピングされるため、ロールバックの実行前にアグリゲートの所有権を元に戻す必要があります。



 a| 
移行したアグリゲートでのボリュームの作成
 a| 
作成したボリュームを削除するか、別のアグリゲートに移動する必要があります。



 a| 
アグリゲートまたはボリュームの名前を変更してい
 a| 
アグリゲートまたはボリュームの名前を元の名前に変更します。



 a| 
RAID タイプを変更しています
 a| 
7-Mode にロールバックする場合は、 RAID タイプが 7-Mode の RAID タイプと同じである必要があります。

|===
* 関連情報 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"]
