---
permalink: copy-free/concept_how_you_can_use_assessment_executive_summary_for_transition_assessment.html 
sidebar: sidebar 
keywords: assessment, ontap, transition, copy, free, executive, summary 
summary: 移行に関するエグゼクティブサマリーには、環境内の 7-Mode コントローラ、ホスト、および FC スイッチの概要が示されます。このサマリーは、現在使用している機能の評価レポートであり、ストレージ環境内の各ボリュームに適した移行方法が提示されます。このサマリーを使用して移行を計画できます。 
---
= 評価のエグゼクティブサマリーを移行に使用する方法 評価
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行に関するエグゼクティブサマリーには、環境内の 7-Mode コントローラ、ホスト、および FC スイッチの概要が示されます。このサマリーは、現在使用している機能の評価レポートであり、ストレージ環境内の各ボリュームに適した移行方法が提示されます。このサマリーを使用して移行を計画できます。

エグゼクティブサマリーは次のセクションで構成されます。



== ターゲットクラスタ

このセクションには、評価時に選択したターゲットクラスタの ONTAP バージョンが表示されます。



== データ収集サマリー

情報を収集した 7-Mode コントローラ、ホスト、およびスイッチの一覧が表示されます。7-Mode コントローラの ONTAP バージョンとモデルの詳細を確認することができます。ホストの OS タイプ、バージョン、モデルも確認できます。



== 移行の可否と推奨される移行方法

このセクションには、各コントローラで実行された事前確認の概要と、コントローラレベルおよびボリュームレベルでの移行の可否が表示されます。「最も上」または「不整合」状態の vFiler ユニットに属するボリューム、またはオフラインまたは制限状態のボリュームは、評価の対象となりません。このレポートには、各コントローラに対する事前確認で報告されたエラーと警告の数が表示されます。移行の前に、これらのエラーと警告を確認し、問題を解決する必要があります。事前確認の詳細については、評価ワークブックの Config Precheck Summary タブを参照してください。

* Copy-Free Transition の可否 * ：このセクションには、 Copy-Free Transition に関するエラーや警告が発生したコントローラレベルの事前確認の数が表示されます。HA ペア内のいずれか 1 つのコントローラに関してでも事前確認が失敗した場合、 Copy-Free Transition を使用してその HA を移行することはできません。エラーおよび警告をすべて解決してから、 HA ペアを移行する必要があります。これらの事前確認の詳細については、評価ワークブックの CFT 事前確認の概要タブを参照してください。

エグゼクティブサマリーには、ボリュームとコントローラの構成および事前確認サマリーに基づいて、評価された各ボリュームに対する最適な移行方法が示されます。たとえば、 7-Mode のトラディショナルボリュームや FlexCache ボリュームは、 ONTAP でサポートされていないため移行できません。

ほとんどの構成に対しては、 7-Mode Transition Tool が移行ツールとして推奨されます。ただし、 7-Mode Transition Tool で移行できないワークロードについては、アプリケーションベースまたはホストベースのマイグレーション方法を使用する必要があります。

http://["ネットアップテクニカルレポート 4052 ：『 Successfully Transitioning to Clustered Data ONTAP （ Data ONTAP 8.2.x and 8.3 ）』"]



== ストレージインベントリ

このセクションでは、次の情報について説明します。

* ストレージオブジェクト：ボリューム、 qtree 、 LUN 、 vFiler ユニットなどのストレージオブジェクトの数に関する情報が表示されます。 各コントローラの SnapMirror 関係、共有、エクスポート。
* Storage utilization ：使用済みスペース、使用可能スペース、および 7-Mode コントローラによって使用されているスペースに関する情報が表示されます。
* Licenses ：各コントローラで有効になっている機能ライセンスの一覧が表示されます。
* プロトコルの設定： CIFS 、 NFS 、 SAN の各プロトコル、バージョンなど、コントローラで設定されているプロトコルに関する詳細が表示されます。
* SnapMirror の相互接続： SnapMirror 関係のソースまたはデスティネーションであるコントローラまたはボリュームに関する情報が表示されます。
+
この情報から、レポートに表示されているコントローラと SnapMirror 関係にあるものの、評価の対象には含まれていないコントローラを特定できます。

* SnapVault の相互接続：コントローラ、ボリューム、またはコントローラ内の指定したコントローラ、ボリューム、または qtree との SnapVault 関係のソースまたはデスティネーションであるコントローラ、ボリューム、または qtree に関する情報が表示されます。




== データ収集エラー

このセクションには、 7-Mode Transition Tool で収集できなかったコントローラとホストの情報、および収集に失敗した理由が表示されます。データ収集エラーの詳細については、評価ワークブックの [ データ収集エラー ] タブを参照してください。これらのエラーを解決し、システムを再評価することができます。
