---
permalink: copy-free/concept_requirements_for_copy_free_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, requirements 
summary: Copy-Free Transition の対象となる 7-Mode システム、クラスタ、 ONTAP リリース、およびディスクシェルフの要件を理解しておく必要があります。 
---
= Copy-Free Transition の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Copy-Free Transition の対象となる 7-Mode システム、クラスタ、 ONTAP リリース、およびディスクシェルフの要件を理解しておく必要があります。

サポートされるターゲットリリースおよび既知の問題に関する最新情報については、最新の 7-Mode Transition Tool リリースノートを参照してください。

link:https://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["『 7-Mode Transition Tool Release Notes 』"]

* * プラットフォームモデル *
+
コピーフリーの移行は、ミッドエンドとハイエンドの FAS システムおよび IBM N シリーズシステムでのみサポートされます。。 https://["NetApp Interoperability Matrix Tool で確認できます"] 7-Mode システムとターゲットクラスタノードでサポートされるプラットフォームの最新情報を用意します。

* * 7-Mode ソースシステムでの Data ONTAP *
+
7-Mode Transition Tool によるマイグレーションでサポートされる 7-Mode のリリースのリストについては、を参照してください https://["NetApp Interoperability Matrix Tool で確認できます"]

* * ONTAP ターゲット・システム *
+
7-Mode Transition Tool バージョン 3.3.1 では、コピーフリー方式を使用した次の ONTAP リリースへの移行がサポートされます。

+
** ONTAP 9.4 以前の ONTAP 9 リリース
** clustered Data ONTAP 8.3.2 以降の 8.x リリース * 注： * コピーフリーの方法を使用して 7-Mode Transition Tool を ONTAP 9.5 以降に移行することはできません。そのためには、まず 7-Mode Transition Tool 3.3.1 を使用した ONTAP 9.4 に移行してから、クラスタを ONTAP 9.5 以降にアップグレードする必要があります。7-Mode Transition Tool 3.3.2 では、コピーフリーの移行はサポートされていません。


* * HA 構成 *
+
7-Mode コントローラとターゲットクラスタノードが HA 構成になっている必要があります。HA ペアが正常に動作している必要があります。また、テイクオーバーモードになっているノードがある場合は移行できません。スタンドアロンコントローラでは、コピーフリーの移行がサポートされません。

* * ディスク・シェルフ・モデル *
+
次のディスクシェルフモデルがサポートされています。

+
** DS4486
** DS4246
** DS4243
+

NOTE: ONTAP 9.2 および ONTAP 9.4 では、ディスクシェルフモデル DS4243 がサポートされません。このモデルは、 ONTAP 9.2P1 以降のすべての ONTAP 9.2 パッチリリースおよび ONTAP 9.3 でサポートされます。7-Mode Transition Tool 3.3.1 では、ディスクシェルフモデル DS4243 での ONTAP 9.2P1~ONTAP 9.3 へのコピーフリーの移行がサポートされます。

** DS2246
** DS14mk4 FC （ ONTAP 9.0 以降ではサポートされません）
** DS14mk2 AT （ ONTAP 9.0 以降ではサポートされません）





NOTE: ディスクシェルフモデル DS14mk2 FC はサポートされません。

* * ディスクファームウェア *
+
最新の Disk Qualification Package 、ディスクファームウェア、およびディスクシェルフと ACP のファームウェアを 7-Mode システムとターゲットクラスタノードにダウンロードしてインストールする必要があります。

+
https://["ネットアップのダウンロード： Disk Qualification Package"]

+
https://["ネットアップのダウンロード：ディスクドライブファームウェア"]

+
https://["ネットアップのダウンロード：ディスクシェルフファームウェア"]

* * ケーブル接続を確認するツール *
+
移行時に 7-Mode ディスクシェルフをターゲットクラスタノードに接続したあと、 Config Advisor を使用してケーブル接続を検証する必要があります。

+
https://["ネットアップのダウンロード： Config Advisor"]


