---
permalink: copy-free/concept_aggregate_space_considerations_during_transition.html 
sidebar: sidebar 
keywords: transition, copy, free, aggregate, space, requirements 
summary: 移行の前に、 7-Mode アグリゲートに十分な空きスペースがあることを確認する必要があります。7-Mode Transition Tool は、物理スペース、論理スペース、 Snapshot コピーの占有スペース、およびスペースギャランティの設定に基づいて、アグリゲートに対してさまざまなスペースチェックを実行します。また、 Flash Pool アグリゲートのスペースに関する考慮事項も把握しておく必要があります。 
---
= 移行でのアグリゲートスペースの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行の前に、 7-Mode アグリゲートに十分な空きスペースがあることを確認する必要があります。7-Mode Transition Tool は、物理スペース、論理スペース、 Snapshot コピーの占有スペース、およびスペースギャランティの設定に基づいて、アグリゲートに対してさまざまなスペースチェックを実行します。また、 Flash Pool アグリゲートのスペースに関する考慮事項も把握しておく必要があります。



== アグリゲートの物理スペース

7-Mode アグリゲートの空きスペースが物理スペースの 5% 未満の場合は、移行がブロックされます。移行前に、 7-Mode アグリゲートに 20% 以上の空きスペースを確保することを推奨します。

アグリゲートには、次の理由で追加のスペースが必要です。

* 実行中に、 7-Mode アグリゲートごとにアグリゲートレベルの Snapshot コピーを作成します エクスポートフェーズ
* 移行したアグリゲート上のワークロードを新しいデータでテストします テストフェーズ


十分なスペースがない場合は、移行前に 7-Mode システムにディスクを追加できます。ディスクの追加が現実的でない場合や、テストフェーズの際に移行したボリュームに書き込まれるデータがごく少量であることが確実な場合は、このエラーを承認して移行を続行できます。ただし、移行中も引き続きアグリゲートのスペースを監視して、テストフェーズでアグリゲートが拡張しないようにする必要があります。



== アグリゲートの論理スペース

7-Mode アグリゲートの論理スペースが 97% 以上使用されている場合、 7-Mode Transition Tool の事前確認でエラーが生成されます。計画フェーズではこのエラーを無視して移行を続行できます。 ただし、アグリゲート内のボリュームのサイズを縮小するか、アグリゲートにディスクを追加して、エクスポートおよび停止処理の前に使用される論理スペースを 97% 未満にする必要があります。エクスポートおよび停止フェーズではこのエラーを無視できません。



== Snapshot オーバーフロー

7-Mode アグリゲート内の Snapshot コピーが Snapshot コピーリザーブよりも多くのスペースを占有している場合は、エクスポートおよび停止処理でアグリゲートレベルの Snapshot コピーの作成が失敗する可能性があります。7-Mode Transition Tool の事前確認では、この状況に対してエラーが生成されます。その場合、アグリゲートレベルの既存の Snapshot コピーを計画フェーズですべて削除する必要があります。

既存の Snapshot コピーを削除したくない場合は、計画フェーズではこのエラーを無視して移行を続行できます。ただし、エクスポートおよび停止処理の前までに、 Snapshot コピーの使用済みスペースを 100% 未満にしておく必要があります。



== スペースギャランティの設定

7-Mode コントローラのボリュームに次のスペースギャランティが設定されている場合、 7-Mode Transition Tool の事前確認でエラーが生成されます。

* ギャランティが無効になっているボリューム
* 設定が file のボリューム
* * ボリュームギャランティが設定されたボリュームで、ギャランティが無効になっています *
+
アグリゲートのスペース不足が原因で、設定が volume のボリュームのスペースギャランティが無効になっている場合があります。

+
7-Mode アグリゲートに十分な空きスペースを作成してから、次の 7-Mode コマンドを使用して該当する 7-Mode ボリュームのスペースギャランティを有効にする必要があります。

+
'*vol options _volume_name _guarantee volume *

+
7-Mode で上記の対処策を実行したくない場合は、このエラーを無視できます。移行が完了したら、ギャランティが無効になっているボリュームを確認し、次のコマンドを使用してギャランティを手動で有効にします。

+
`* volume modify -vserver -volume -space-guarantee volume *`

* * ファイルギャランティが設定されたボリューム *
+
ファイルギャランティは ONTAP ではサポートされていません。

+
ギャランティが file のボリュームがある場合は、次のいずれかを実行する必要があります。

+
** 7-Mode ボリュームにスペースリザーブの LUN またはファイルが含まれている場合は、 7-Mode コマンド： +`*vol options_volume_name _guarantee volume *` を使用して、ボリュームのスペースギャランティのタイプを volume に変更します
+
このコマンドを実行する前に、 7-Mode アグリゲートに十分な空きスペースがあることを確認する必要があります。

** 7-Mode ボリュームにスペースリザーブの LUN またはファイルが含まれていない場合は、次の 7-Mode コマンドを使用してボリュームのスペースギャランティを none に変更します。 +`*vol options _volume_name _guarantee none*7-Mode で修正措置を実行しない場合は、このエラーを無視して移行を続行できます。


+
移行中に、これらのボリュームにスペースリザーブ LUN またはファイルが含まれている場合、スペースギャランティは自動的に「 volume 」に変換されますが、スペースギャランティは最初は無効になります。アグリゲートに十分な空きスペースを作成してから、次のコマンドを使用して手動でギャランティを有効にする必要があります。

+
+`* volume modify -vserver -volume -space-guarantee volume *`

+
+ ボリュームにスペースリザーブの LUN またはファイルが含まれていない場合は、移行中にスペースギャランティが自動的に none に変換されます。





== Flash Pool アグリゲートに関するその他の考慮事項を示します

Flash Pool アグリゲートの SSD の空きスペースが SSD の合計ディスクスペースの 5% 未満の場合、移行はサポートされません。移行を続行するには、 SSD キャッシュを無効にするか、 SSD を追加する必要があります。

* 関連情報 *

xref:reference_ignorable_errors_during_transition.adoc[移行時に無視できるエラーです]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"]
