---
permalink: copy-free/concept_transition_overview.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, overview 
summary: clustered ONTAP への移行では、現在の環境を確認し、移行対象を決定するとともに、デスティネーションシステムの最適な構成を設計し、データと構成のマイグレート方法を計画し、必要に応じて環境を更新します。 
---
= 移行の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
clustered ONTAP への移行では、現在の環境を確認し、移行対象を決定するとともに、デスティネーションシステムの最適な構成を設計し、データと構成のマイグレート方法を計画し、必要に応じて環境を更新します。

サポートされるターゲットリリースおよび既知の問題に関する最新情報については、最新の 7-Mode Transition Tool リリースノートを参照してください。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-72c-rn/home.html["『 7-Mode Transition Tool Release Notes 』"]

最初に、現在のストレージ環境、ホスト、およびアプリケーションを含む、現在の環境に関する情報を収集する必要があります。ストレージインベントリを収集したら、現在使用している機能を評価し、選択した ONTAP バージョンとの相違点を確認します。これらの作業は、 7-Mode Transition Tool を使用して実行できます。

その後、移行プロジェクトを定義できます。この作業では、同時に移行するボリュームとワークロードを特定し、クラスタを設計して移行を計画します。マイグレーションの計画では、まず最適なマイグレーション方式を選択します。クラスタを設計する際には、収集したストレージ環境情報を使用して、既存の構成項目を ONTAP の対応する項目にマッピングします。たとえば、 7-Mode ボリュームは ONTAP 内の SVM とボリュームにマッピングする必要があり、移行対象の IP アドレスは LIF にマッピングする必要があります。また、 ONTAP システムに対して環境の変更が必要かどうかも確認します。

実装作業には、必要な環境変更を実施するだけでなく、クラスタの導入と設定、データのマイグレート、変更された構成の適用、デスティネーション ONTAP システムからのクライアントの切断と再接続、アクセスの検証が含まれます。

* 関連情報 *

http://docs.netapp.com/ontap-9/index.jsp["ネットアップのマニュアル： ONTAP 9"]
