---
permalink: copy-free/task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, find, remove, volumes, snapshot, copy 
summary: すべてのアグリゲートを 64 ビット形式に拡張した場合でも、 32 ビット形式または混在形式の FlexVol ボリュームや Snapshot コピーが残っている可能性があります。Data ONTAP 8.3 以降を実行するクラスタからデータにアクセスするには、このようなボリュームや Snapshot コピーを削除する必要があります。 
---
= 32 ビットボリュームと Snapshot コピーの検出と削除
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのアグリゲートを 64 ビット形式に拡張した場合でも、 32 ビット形式または混在形式の FlexVol ボリュームや Snapshot コピーが残っている可能性があります。Data ONTAP 8.3 以降を実行するクラスタからデータにアクセスするには、このようなボリュームや Snapshot コピーを削除する必要があります。

* システム上のすべての 32 ビットアグリゲートを 64 ビット形式に拡張しておく必要があります。


このタスクの手順は、 32 ビットボリュームと Snapshot コピーを含むアグリゲートごとに繰り返す必要があります。

.手順
. advanced モードに切り替えます。
+
「 * priv set advanced * 」と入力します

. アグリゲート内のすべてのボリュームの形式を表示します。
+
`*aggr 64bit-upgrade status_aggr_name -- all*`

+
アグリゲート内の各ボリュームとその形式が表示されます。

. 32 ビット形式または混在形式のボリュームごとに、ボリュームが 64 ビット形式に拡張されていない理由を確認し、適切な操作を実行します。
+
ボリュームが拡張されなかった理由を特定できない場合は、アグリゲートの拡張を再試行します。

+
|===
| ボリュームの状況 | 作業 


 a| 
は、 SnapMirror 関係のデスティネーションです
 a| 
ソースボリュームを含むアグリゲートを 64 ビット形式に拡張します。



 a| 
読み取り専用ボリューム（ただし SnapMirror デスティネーションではない）
 a| 
ボリュームを書き込み可能にして拡張を再試行するか、ボリュームを削除します。



 a| 
に十分な空きスペースがないため、拡張されませんでした ボリュームまたはアグリゲート
 a| 
ボリュームまたはアグリゲートの空きスペースを増やして拡張を再試行します。

|===
+
これでアグリゲート内の 32 ビットボリュームと混在形式のボリュームがすべて 64 ビットになります。これは、前の手順を繰り返して確認できます。

. システム上のすべての Snapshot コピーの形式を表示します。
+
`*snap list -fs-block-format*`

. snap delete コマンドを使用して 32 ビット Snapshot コピーを削除します。
+

IMPORTANT: この操作では、 Snapshot コピー内のデータが削除されます。削除しようとしている Snapshot コピーを残しておく必要がないことを必ず確認してください。また、 32 ビット Snapshot コピーが期限切れになるまで待つこともできます。この処理にかかる時間は、 Snapshot コピーのスケジュールによって異なります。

+
FlexClone ボリュームのベースの Snapshot コピーである Snapshot コピーを削除する場合は、 FlexClone ボリュームをその親からスプリットしておく必要があります。

+
32 ビット Snapshot コピーがすべて削除されます。これは、前の手順を繰り返して確認できます。

. admin 権限レベルに戻ります。
+
`*priv set admin*`


