---
permalink: copy-free/task_running_prechecks.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, runn, prechecks 
summary: 移行を開始する前に、事前確認を実行して問題を特定することができます。事前確認では、ソースの 7-Mode 、ターゲットの ONTAP 、および構成が移行対象として適切かどうかが検証されます。事前確認は何度でも実行できます。 
---
= 事前確認を実行
:icons: font
:imagesdir: ../media/


[role="lead"]
移行を開始する前に、事前確認を実行して問題を特定することができます。事前確認では、ソースの 7-Mode 、ターゲットの ONTAP 、および構成が移行対象として適切かどうかが検証されます。事前確認は何度でも実行できます。

事前確認では 200 以上のチェックが実行されます。たとえば、ボリュームがオンラインかどうか、システム間にネットワークアクセスが存在するかどうかなどがチェックされます。

. ダッシュボードで、事前確認を実行するプロジェクトを選択します。
. 「 * 事前チェックを実行 * 」をクリックします。
+
事前確認が完了すると、結果の概要がダイアログボックスに表示されます。

+

NOTE: 一般に事前確認は数分程度で終了しますが、解決が必要なエラーや警告の件数と種類によって実行時間は変わります。



.手順
. [ タイプフィルタを適用（ Apply Type Filter ） ] でオプションを選択して、結果をフィルタ処理します。
+
** セキュリティに関連するすべてのメッセージを表示するには、 * エラー * 、 * 警告 * 、 * 情報 * 、および * セキュリティのみ * を選択します。
** セキュリティに関連するすべてのエラーメッセージを表示するには、「 * エラー * 」および「 * セキュリティのみ * 」を選択します。
** セキュリティに関連するすべての警告メッセージを表示するには、 [** 警告 ** （ Warning ** ） ] および [ セキュリティのみ * （ Security Only * ） ] を選択します。
** セキュリティに関連するすべての情報メッセージを表示するには、 * 情報 * および * セキュリティのみ * を選択します。


. 生の結果をカンマ区切り値（ CSV ）形式で保存し、結果をエクスポートするには、 * CSV として保存 * をクリックします。
+
移行中に実行された移行処理を、処理のタイプ、ステータス、開始時刻、終了時刻、結果とともにダッシュボードペインの Operation History タブで確認できます。



データコピーを開始する前に、事前確認で検出されたエラーをすべて解決する必要があります。また、マイグレーションプロセスに進む前にすべての警告を解決しておくことを推奨します。解決策としては、警告メッセージのソース問題を解決するか、回避策を実装するか、問題の結果を受け入れます。
