---
permalink: copy-free/task_selecting_lifs_to_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, select, lif 
summary: 必要に応じて、移行後に SVM で設定する LIF を指定できます。7-Mode システムで使用している既存の IP アドレス、または新しい LIF を指定できます。移行されるのは NAS LIF のみです。FC LIF と iSCSI LIF は、 SVM のプロビジョニングフェーズの前に手動で設定しておく必要があります。 
---
= 移行する LIF を選択しています
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、移行後に SVM で設定する LIF を指定できます。7-Mode システムで使用している既存の IP アドレス、または新しい LIF を指定できます。移行されるのは NAS LIF のみです。FC LIF と iSCSI LIF は、 SVM のプロビジョニングフェーズの前に手動で設定しておく必要があります。

移行対象として選択した LIF は、次のいずれかの方法で、 SVM のプロビジョニングフェーズ中に SVM に設定されます。

* 移行対象として選択した既存の 7-Mode IP アドレスが、管理状態が down で作成されます。
+
これらの IP アドレスは、カットオーバーが開始されるまでは引き続き 7-Mode でデータを提供できます。インポートフェーズでは、これらの IP アドレスが管理状態が up で設定されます。

* 新しい IP アドレスは管理状態が up で作成されます。
+
SVM のプロビジョニングフェーズ後、作成された LIF を使用して SVM からネームサーバへの接続をテストできます。



.手順
. LIF の設定タブで、次のいずれかのオプションを選択します。
+
|===
| 移行対象 | 作業 


 a| 
7-Mode システムの既存の IP アドレス
 a| 
.. Select 7-Mode LIF * をクリックします。
.. 移行する IP アドレスを選択し、ターゲット SVM とその他のネットワークパラメータを指定します。
.. [ 保存（ Save ） ] をクリックします。




 a| 
新しい IP アドレス
 a| 
.. Add New LIF * をクリックします。
.. 設定する IP アドレス、ターゲット SVM 、およびその他のネットワークパラメータを指定します。
.. [ 保存（ Save ） ] をクリックします。


|===
+

NOTE: ターゲットポートは、ターゲット SVM と同じ IPspace に属している必要があります。

. 「 * 次へ * 」をクリックします。
+
[Plan Configuration] タブが表示されます。


