---
permalink: copy-free/task_testing_workloads_and_applications.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, test, workload, application 
summary: すべてのワークロードとアプリケーションをテスト運用環境で手動でテストする必要があります。その後、プロジェクトをコミットする前に短期間だけ運用を開始して、ロールバックが必要かどうかを評価できます。 
---
= ワークロードとアプリケーションのテスト
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのワークロードとアプリケーションをテスト運用環境で手動でテストする必要があります。その後、プロジェクトをコミットする前に短期間だけ運用を開始して、ロールバックが必要かどうかを評価できます。

移行したアグリゲートに 5% 以上の物理的な空きスペースが必要です。


NOTE: 20% 以上の空きスペースを確保することを推奨します。

テストでは一部の処理が制限されます。

xref:concept_restrictions_during_preproduction_testing.adoc[テスト時の制限事項]

.手順
. 移行したボリュームにクライアントを接続します。
. SAN ワークロードがある場合は、移行後のホスト修正タスクを SAN ホストで実行します。
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-sanspl/home.html["SAN ホストの移行および修復"]

. 移行したデータと構成を使用するすべてのワークロードとアプリケーションをテストします。
. 移行したアグリゲートの空き物理スペースを 7-Mode Transition Tool ダッシュボードのアグリゲートタブで監視して、移行したアグリゲートのスペースが不足していないことを確認します。
+
* トラブルシューティング： * 移行したアグリゲートのスペースが不足している場合は、ディスクを追加できます。

+
.. advanced 権限レベルにログインします。 +`*set -privilege advanced *`
.. 7-Mode ディスクシェルフからスペアディスクを選択してディスクを追加し、移行したアグリゲートのスペースを増やします。 +`* storage aggregate add-disks -aggregate _aggr_name -diskdisk1_*`
+
7-Mode のスペアディスクを使用できない場合は、クラスタノードのディスクシェルフにあるスペアディスクを使用できますが、ロールバックプロセスが複雑になります。





本番環境のデータの提供を開始できます。

[IMPORTANT]
====
短期間だけ本番環境でデータを提供して、ワークロードが本番環境で正しく処理されていること、および 7-Mode へのロールバックが不要であることを確認します。次の理由により、このフェーズを延長すること、およびコピーフリーの移行プロジェクトのコミットを遅らせることはするべきではありません。

* 新しいデータがボリュームに書き込まれると、移行したアグリゲートのスペースが不足する可能性が高くなる。
* この間にボリュームに書き込まれた新しいデータはロールバック中に使用できなくなります。


====
* 関連情報 *

xref:concept_reverting_a_copy_free_transition_project.adoc[7-Mode への移行のロールバックの実行]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"]
