---
permalink: copy-free/task_applying_svm_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, apply, svm, configurations 
summary: SVM のプロビジョニングフェーズの前に、一部の構成を手動で適用する必要があります。その後、ツールを使用して、 7-Mode コントローラで定義されている構成（ /etc ディレクトリ内のファイル）または vFiler ユニットレベルで定義されている構成をすべて、マッピングされた SVM に適用できます。 
---
= SVM 構成を適用しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM のプロビジョニングフェーズの前に、一部の構成を手動で適用する必要があります。その後、ツールを使用して、 7-Mode コントローラで定義された構成（「 /etc 」ディレクトリ内のファイル）または vFiler ユニットレベルで定義された構成をすべて、マッピングされた SVM に適用できます。

すべての構成をターゲット SVM に移行しない場合は、 SVM に除外する構成のプロパティを設定しておく必要があります。

xref:task_customizing_configurations_for_transition.adoc[7-Mode 構成の移行のカスタマイズ]

* NFS エクスポート、 CIFS 共有、 LUN マッピングなどの構成は、 SVM のプロビジョニングフェーズで SVM に適用されません。
* SVM のプロビジョニングフェーズでツールによって SVM に適用される構成は次のとおりです。
+
** * ネームサービス *
+
*** DNS の設定
*** LDAP の設定
*** NIS の設定
*** ネームサービススイッチの設定
*** ホストの構成
*** UNIX ユーザおよびグループ
*** ネットグループの構成


** * ネットワーク *
+
*** 移行対象として選択した既存の 7-Mode IP アドレスが、管理状態が down で作成されます。
+
インポートフェーズでは、これらの IP アドレスが管理状態が up で設定されます。

*** 新しい IP アドレスは管理状態が up で作成されます。


** * NFS *
+
NFS オプション

** * CIFS *
+
*** CIFS の優先 DC 構成
*** ユーザマッピングの構成
*** ワイドリンクの構成
*** CIFS オプション
*** 監査設定


** * SAN*
+
FC および iSCSI サービス

+
[IMPORTANT]
====
正常に完了した場合、この処理は再実行できません。

そのため、処理の完了後に 7-Mode コントローラレベルの構成を変更した場合は、エクスポートフェーズの前にターゲット SVM に手動で構成を移行する必要があります。たとえば、この処理の完了後に、 7-Mode コントローラに新しい vFiler ユニットを追加して SVM にマッピングした場合は、その vFiler ユニットの構成をマッピングした SVM に手動で移行する必要があります。あるいは、 SVM のプロビジョニングフェーズ後に 7-Mode コントローラに UNIX ユーザを追加した場合は、マッピングした SVM で該当する UNIX ユーザを手動で作成する必要があります。

====




.手順
. Apply SVM Config * をクリックして、 7-Mode 構成をターゲット SVM に適用します。
+
この処理に関する重要な考慮事項を記載した確認メッセージが表示されます。

. 続行するには、 [ はい ] をクリックします。
. 処理が完了したら、次の手順を実行します。
+
.. [ * CSV として保存 * （ Save as CSV * ） ] をクリックして、操作結果をファイルに保存します。
.. プロジェクトログの収集 * をクリックして、すべての移行ログファイルのバックアップを作成します。
+
移行処理を実行するたびにログファイルを保存することを推奨します。

.. [ 閉じる（ Close ） ] をクリックして、 [ 操作結果（ Operation Results ） ] ウィンドウを閉じる。


+
処理の完了に時間がかかる場合は、 * バックグラウンドで実行 * をクリックすると、処理結果ウィンドウを終了できます。バックグラウンドで処理を実行している間は、プロジェクトを編集したり他のタスクを実行したりしないでください。その後、 [ 操作履歴（ Operation History ） ] タブで操作結果を表示できます。

. ターゲット SVM に適用された構成を手動で検証およびテストして、必要な変更を行います。
. 外部ネームサーバへの接続を手動で検証します。

