---
permalink: copy-free/task_performing_a_transition_rollback.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, roll, back, project 
summary: 移行したアグリゲートをコミットする前であれば、コピーフリーの移行のどのフェーズでも、移行をロールバックして 7-Mode にリバートできます。ロールバックは手動で行います。7-Mode Transition Tool を使用して、ロールバックで実行する必要のある手動の手順を生成できます。 
---
= コピーフリーの移行プロジェクトをロールバックしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行したアグリゲートをコミットする前であれば、コピーフリーの移行のどのフェーズでも、移行をロールバックして 7-Mode にリバートできます。ロールバックは手動で行います。7-Mode Transition Tool を使用して、ロールバックで実行する必要のある手動の手順を生成できます。

* ボリュームまたはアグリゲートの移行処理がクラスタで実行されていないことを確認します。
+
「 job show -jobtype transition 」コマンドを使用できます。

* コミットされた 7-Mode アグリゲートがないことを確認します。
+

NOTE: 7-Mode アグリゲートが 1 つでもコミットされていると、ロールバックを実行できません。

* ターゲットクラスタノードがテイクオーバーモードでないことを確認します。


.手順
. ロールバック (Rollback Precheck) * をクリックして ' プロジェクトがロールバックの対象であることを確認します
+
事前確認で問題が報告された場合は、それらを手動で修正し、事前確認処理を再実行する必要があります。たとえば、テスト時に新しいボリュームまたは LUN を作成した場合は手動で削除する必要があります。

. [ ロールバックステップの生成（ Generate Rollback Steps ） ] をクリックして、ロールバックを成功させるために実行する必要がある手動ステップのリストを生成します。
. * Save as CSV * （ CSV として保存）をクリックして、手動ステップをファイルに保存します。
+
ファイルからロールバックコマンドをコピーして実行できます。

. どの移行フェーズからロールバックするかに応じて、必要な手動手順を実行します。
+
** * インポートまたはテストフェーズ *
+
... クラスタでロールバックコマンドを実行し、 * 確認 * をクリックします。
... 7-Mode ディスクシェルフを 7-Mode コントローラに接続し、ケーブル接続を手動で検証して、 * Confirm * をクリックします。
... 7-Mode コントローラでロールバックコマンドを実行し、 * Confirm * をクリックします。
... Operations History タブで、 SVM に適用されている構成を表示します。
... ツールによって適用されたすべての構成を SVM から手動で削除します。


** * 配線フェーズ *
+
... 7-Mode ディスクシェルフを 7-Mode コントローラに接続し、ケーブル接続を手動で検証して、 * Confirm * をクリックします。
+
7-Mode のケーブル接続が、プロジェクト開始時と同じ状態であることを確認する必要があります。

+

NOTE: ケーブル接続を検証するには、 Config Advisor を使用する必要があります。

... 7-Mode コントローラでロールバックコマンドを実行し、 * Confirm * をクリックします。
... ツールによって適用されたすべての構成を SVM から手動で削除します。
+
SVM に適用されている設定は、 Operations History タブで確認できます。



** * エクスポートフェーズ *
+
... 7-Mode コントローラでロールバックコマンドを実行し、 * Confirm * をクリックします。
... ツールによって適用されたすべての構成を SVM から手動で削除します。
+
SVM に適用されている設定は、 Operations History タブで確認できます。



** * SVM のプロビジョニングフェーズ *
+
ツールによって適用されたすべての構成を SVM から手動で削除します。

+
SVM に適用されている設定は、 Operations History タブで確認できます。



+
xref:task_running_manual_steps_for_rolling_back_transition.adoc[移行をロールバックするための手動手順]

. すべての手動手順が完了したら、 7-Mode Transition Tool で * Verify 7-Mode * をクリックして、 7-Mode コントローラでデータを提供する準備ができていることを確認します。

