---
permalink: copy-free/task_verifying_readiness_for_cutover.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, verify, cutover, ready, systems 
summary: クライアントアクセスを切断する前に、 7-Mode システムのストレージカットオーバーの準備状況を検証できます。たとえば、 SP または RLM が 7-Mode システムで設定されているかどうか、ディスクシェルフ、アグリゲート、ボリュームの移行準備ができているかどうかを検証します。エクスポート処理の前に問題を手動で修正することで、ダウンタイムを短縮できます。 
---
= 7-Mode システムのカットオーバーの準備状況の検証
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントアクセスを切断する前に、 7-Mode システムのストレージカットオーバーの準備状況を検証できます。たとえば、 SP または RLM が 7-Mode システムで設定されているかどうか、ディスクシェルフ、アグリゲート、ボリュームの移行準備ができているかどうかを検証します。エクスポート処理の前に問題を手動で修正することで、ダウンタイムを短縮できます。

この処理は、エクスポートおよび停止処理を開始する前であれば何度でも実行できます。

.手順
. Check Readiness * をクリックして、 7-Mode システムをカットオーバーする準備ができていることを確認します。
+
この処理はオプションですが、ストレージカットオーバー期間を最小限に抑えるには、エクスポート処理の前にシステムの準備状況を検証して、問題を修正しておくことを推奨します。

. 処理が完了するまで待ってから、次の手順を実行します。
+
.. [ * CSV として保存 * （ Save as CSV * ） ] をクリックして、操作結果をファイルに保存します。
.. ツールログの収集 * をクリックして、すべての移行ログファイルのバックアップを作成します。
+
移行処理を実行するたびにログファイルを保存することを推奨します。

.. [ 閉じる（ Close ） ] をクリックして、 [ 操作結果（ Operation Results ） ] ウィンドウを閉じる。


+
処理の完了に時間がかかる場合は、 * バックグラウンドで実行 * をクリックすると、処理結果ウィンドウを終了できます。バックグラウンドで処理を実行している間は、プロジェクトを編集したり他のタスクを実行したりしないでください。その後、 [ 操作履歴（ Operation History ） ] タブで操作結果を表示できます。


