---
permalink: copy-free/task_generating_an_assessment_report_by_adding_systems_to_7mtt.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, assessment, report, add, transition, tool 
summary: 7-Mode Transition Tool にシステムを追加することで、コントローラ、ホスト、および FC スイッチのインベントリ情報を収集できます。そのあとに評価レポートを作成して、追加したシステムの機能を評価するとともに、移行先として選択した ONTAP バージョンでそれらの機能がどのように動作するかを確認できます。 
---
= 7-Mode にシステムを追加することによる評価レポートの作成 移行ツール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool にシステムを追加することで、コントローラ、ホスト、および FC スイッチのインベントリ情報を収集できます。そのあとに評価レポートを作成して、追加したシステムの機能を評価するとともに、移行先として選択した ONTAP バージョンでそれらの機能がどのように動作するかを確認できます。

* ストレージシステムおよびホストのユーザ名が、 readme ファイルに示されたコマンドを実行するための権限を持っている必要があります。
+
readme ファイルは '_7-Mode_Transition_Tool_installed_location \bin\tic' にあります

* 移行のための環境評価を実行できるように、 7-Mode システム、ホスト、および FC スイッチを準備しておきます。
* Windows システムを評価する場合は、ドメインユーザアカウントが必要です。
* 評価用に複数のシステムを追加する場合は、 ASCII 形式または UTF-8 形式でエンコードされたテキストファイルを作成し、 1 行に 1 つのシステムの形式でシステムの詳細を含める必要があります。
+
各システムの詳細を次の形式で記述する必要があります。

+
'(ontap|windows|vmware|linux-cisco|brocade) ： // （ _user|domain_user_） [_ ： password_]@] （ _host_name|IP_

* 7-Mode Transition Tool をインストールおよび実行するシステムから、コントローラまたはホストにアクセスできる必要があります。
* すべての機能に関するインベントリ情報をワークブックに記録できるように、それらの機能を設定するか、またはそのライセンスを有効にする必要があります。
* ストレージシステムのユーザ名には、インベントリ情報を収集するための管理者権限が必要です。
* CIFS 共有名、ユーザ名、グループ名など、すべてのホスト名およびストレージシステム構成は、 UTF-8 形式である必要があります。


7-Mode Transition Tool サービスまたはこのツールがインストールされているシステムを再起動すると、ツールに追加したシステムの詳細が失われ、再度ツールにシステムを追加しなければならなくなります。

.手順
. 移行のための環境評価に最新の Interoperability Matrix （ IMT ）データを使用する場合は、次の手順を実行します。
+
.. Interoperability Matrix から IMT データをダウンロードして保存します。
+
... [ レポート ] メニューの [ 日次エクスポートの完了 *] をクリックします。
... ［ 日次エクスポートの完了 ］ ダイアログボックスの検索フィールドに「 FAS 」と入力します。
... ONTAP SAN ホストの Excel ファイルをダウンロードして保存します。https://["NetApp Interoperability Matrix Tool で確認できます"]


.. CLI から 'transition IMT import' コマンドを使用して IMT データをインポートします
.. transition IMT show コマンドを使用して、インポートが正常に完了したことを確認します。
+
* トラブルシューティング： * IMT データ・インポート操作が失敗した場合は 'transition IMT restore' コマンドを使用して ' 以前のデータに戻すことができます



. 7-Mode Transition Tool にログインし、ホームページで * Collect & Assess * をクリックします。
. [ システムの追加 ] をクリックします。
. [Add System] ウィンドウで、次のいずれかの操作を実行します。
+
** システムを 1 つ追加します。
+
... システムの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。
... 指定したシステムのユーザ名とパスワードを入力します。
... システムタイプを選択します。
+
**** Data ONTAP ストレージシステム
**** ホスト： Microsoft Windows 、 Red Hat Linux Enterprise 、 VMware ESXi
**** FC スイッチ： Cisco および Brocade




** 複数のシステムを追加するには、 * 参照 * をクリックし、複数のシステムの資格情報を含むテキストファイルを選択します。


. [ 追加（ Add ） ] をクリックします。
+
評価ステータスが Ready のシステムに対しては、移行のための環境評価を実行できます。

. 移行のための環境評価レポートを作成します。
+
.. 移行のための環境評価を実施するシステムを選択します。
.. Create Transition Assessment Report （移行評価レポートの作成） * をクリックします。
.. Create Transition Assessment Report ダイアログボックスで、ターゲットクラスタの Data ONTAP バージョンを選択します。
.. レポートのファイル名に付けるプレフィックスを指定します。
.. [ レポートの生成（ Generate Report ） ] をクリックする。


+
評価ワークブック（「 AssessmentWorkbook 」が付加されたレポート名）および評価エグゼクティブサマリー（「 AssessmentExecutiveSummary 」が付加されたレポート名）が、 XML 形式で作成されます。

+
+ 評価レポートの作成に使用する評価ワークブック、評価サマリー、およびインベントリ XML ファイルには、「 ...etc/webapp/transition-GUI/tMC 」フォルダからアクセスできます。

. Microsoft Excel の評価ワークブックと、 Microsoft Office 2007 以降のバージョンを使用した Microsoft Word の評価エグゼクティブサマリーを表示します。
+
評価ワークブックで、コピーフリーの移行のための環境評価の詳細について、移行の実現可能性（ CFT ）、事前確認の概要、事前確認の詳細設定、 CFT 事前確認の概要の各タブを参照してください。

+
評価エグゼクティブサマリーでは、コントローラレベルの評価の詳細について、コピーフリーの移行の実現可能性に関するセクションを参照してください。

+
場合によっては、評価ワークブックを表示するために Excel でマクロを有効にする必要があります。

+
評価ワークブックのデータ収集サマリーで、システムのアクセスステータスが「失敗」の場合、そのシステムのインベントリ情報は無効です。評価エグゼクティブサマリーでは、このシステムの一部のフィールドの値は「 Not Assessed 」と表示されます。


