---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: 7-Mode SnapMirror 関係のボリュームを含むプライマリ HA ペアとセカンダリ HA ペアを並行して移行することができます。移行後に、 clustered Data ONTAP で Volume SnapMirror 関係を手動で設定する必要があります。SnapMirror 関係は移行後も維持されます。ベースラインの再設定は必要ありません。 
---
= SnapMirror 関係のプライマリシステムとセカンダリシステムを移行する 平行（ Parallel ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode SnapMirror 関係のボリュームを含むプライマリ HA ペアとセカンダリ HA ペアを並行して移行することができます。移行後に、 clustered Data ONTAP で Volume SnapMirror 関係を手動で設定する必要があります。SnapMirror 関係は移行後も維持されます。ベースラインの再設定は必要ありません。

ソースクラスタとデスティネーションクラスタで SnapMirror 関係を移行する準備をしておく必要があります。

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[クラスタで Volume SnapMirror 関係を移行する準備をしています]

セカンダリとプライマリ両方の HA ペアを、同じカットオーバー期間内に移行する必要があります。

.手順
. 7-Mode Transition Tool から、 7-Mode の Volume SnapMirror 関係のプライマリボリュームとセカンダリボリュームを含む 2 つの HA ペアに対して、コピーフリーの移行を実行します。
+
セカンダリボリュームを含む 7-Mode HA ペアを移行する前に、 7-Mode の SnapMirror 関係に対する手動の操作は必要ありません。これにより、 7-Mode のセカンダリボリュームは、読み取り専用ボリュームとして ONTAP に移行されます。

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[コピーフリーの移行を使用した 7-Mode アグリゲートの移行]

. 移行したプライマリボリュームとセカンダリボリュームを含む SVM 間にクラスタ間 SVM ピア関係を作成します。
+
https://["システム管理"]

. 移行したプライマリボリュームとセカンダリボリュームの間に Volume SnapMirror 関係を作成します。
+
https://["ボリュームディザスタリカバリの簡単な設定"]

. デスティネーションボリュームで、 SnapMirror 関係のソースボリュームとデスティネーションボリュームを再同期します。
+
*snapmirror resync *

+

IMPORTANT: ソースボリュームとデスティネーションボリュームの間には、共通の Snapshot コピーが少なくとも 1 つ必要です。

+
* トラブルシューティング：共通の Snapshot コピーが Data ONTAP 8.1 より前のリリースで作成された場合、 SnapMirror の再同期が失敗します。advanced 権限レベルで '-fs-version' パラメータを volume snapshot show コマンドとともに使用すると ' スナップショット・コピーが作成されたリリースを表示できますこの問題が表示された場合は、 SnapMirror 関係を解除してから再同期を実行します。

. SnapMirror データ転送のステータスを監視します。
+
「 * snapmirror show * 」

+

IMPORTANT: 再同期が完了するまでは、ソースボリュームとデスティネーションボリュームでボリューム移動や SnapMirror 解除などの処理を実行しないでください。再同期は中断せずに正常に完了するようにしてください。中断しないと、ボリュームが不整合状態になる可能性があります。

. セカンダリプロジェクトの移行をコミットしてから、プライマリプロジェクトの移行をコミットします。
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[コピーフリーの移行プロジェクトのコミット]



* 関連情報 *

http://["ONTAP 9 のコマンド"]

https://["System Manager の略"]
