---
permalink: copy-free/task_exporting_7_mode_system_and_hardware_information.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, exporte, storage, configurations, halt 
summary: 移行のカットオーバー期間はエクスポートフェーズから始まります。このフェーズでは、システム情報、ディスクシェルフの詳細、およびストレージ構成が 7-Mode システムから収集され、 7-Mode ストレージシステムが停止します。 
---
= ストレージ構成をエクスポートして 7-Mode システムを停止します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行のカットオーバー期間はエクスポートフェーズから始まります。このフェーズでは、システム情報、ディスクシェルフの詳細、およびストレージ構成が 7-Mode システムから収集され、 7-Mode ストレージシステムが停止します。

* サービスプロセッサ（ SP ）または Remote LAN Module （ RLM ）を、 IPv4 アドレスを使用して 7-Mode システムに設定しておく必要があります。
* すべてのクライアントを 7-Mode システムから切断しておく必要があります（ NFS エクスポートをアンマウントし、 CIFS 共有を切断し、 SAN ホストをシャットダウンします）。ただし、 NAS サービスと SAN サービスは 7-Mode システムで実行されている必要があります。
+

IMPORTANT: プロトコルサービスは 7-Mode ストレージシステムからプロトコルの構成を収集する際に必要なため、停止しないでください。

* この処理中に 7-Mode ボリュームに書き込まれたデータはすべて失われます。
* この処理の実行中は、 7-Mode システムで管理処理を実行しないでください。
* エクスポートフェーズでは、ツールは次の処理を実行します。
+
** ボリュームとストレージの構成をすべて収集します
** 移行する各アグリゲートの Snapshot コピーを作成します
+
移行のいずれかのフェーズで 7-Mode にリバートする場合は、これらの Snapshot コピーがリバート処理に使用されます。

** 7-Mode コントローラをメンテナンスモードでブートします
** 7-Mode コントローラからディスク所有権を削除する
** ターゲットクラスタノードでディスクの自動割り当てを無効にします




.手順
. [ エクスポートおよび停止（ Export & Halt ） ] をクリックします
+
この処理に関する重要な考慮事項を示すメッセージが表示されます。

. [ クライアントアクセスが切断されたことを確認する *] チェックボックスをオンにします。
. [ はい（ * Yes ） ] をクリックして、エクスポートおよび停止操作を続行します。
+
処理結果が表示されます。

. 処理の完了を待って次の手順を実行し、処理結果を保存してツールログを収集します。
+
.. [ * CSV として保存 * （ Save as CSV * ） ] をクリックして、操作結果をファイルに保存します。
.. ツールログの収集 * をクリックして、すべての移行ログファイルのバックアップを作成します。
+
移行処理を実行するたびにログファイルを保存することを推奨します。

.. [ 閉じる（ Close ） ] をクリックして、 [ 操作結果（ Operation Results ） ] ウィンドウを閉じる。


+
処理の完了に時間がかかる場合は、 * バックグラウンドで実行 * をクリックすると、処理結果ウィンドウを終了できます。バックグラウンドで処理を実行している間は、プロジェクトを編集したり他のタスクを実行したりしないでください。その後、 [ 操作履歴（ Operation History ） ] タブで操作結果を表示できます。


