---
permalink: copy-free/task_importing_7_mode_data_to_clustered_ontap.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, import, data 
summary: ケーブル接続を検証して問題をすべて解決したら、インポート処理を実行できます。このフェーズでは、マッピングしたクラスタノードにディスク所有権が割り当てられ、 7-Mode のアグリゲート、ボリューム、および LUN が ONTAP 形式に変換されます。ボリュームレベルおよび LUN レベルの構成がすべて適用されます。 
---
= ONTAP への 7-Mode データのインポート
:icons: font
:imagesdir: ../media/


[role="lead"]
ケーブル接続を検証して問題をすべて解決したら、インポート処理を実行できます。このフェーズでは、マッピングしたクラスタノードにディスク所有権が割り当てられ、 7-Mode のアグリゲート、ボリューム、および LUN が ONTAP 形式に変換されます。ボリュームレベルおよび LUN レベルの構成がすべて適用されます。

このフェーズでは、ツールによって次の処理が実行されます。

* 7-Mode のディスクがマッピングしたターゲットクラスタノードに割り当てられます。
* 7-Mode のアグリゲート、ボリューム、および LUN がすべて、 ONTAP 形式に変換されます。
* 移行対象として選択した 7-Mode IP アドレスが、管理状態が up で SVM に設定されます。
* 次の構成が適用されます。
+
** NFS エクスポートルール
** CIFS 共有
** CIFS ACLs 構成
** CIFS のホームディレクトリ設定
** CIFS シンボリックリンク
** クォータ構成
** Snapshot コピーのスケジュール
** LUN マップと igroup




.手順
. [* インポート * ] をクリックします。
+
* トラブルシューティング： * アグリゲート内のディスクが不足している場合、アグリゲートはデグレード状態になり、インポート処理が失敗します。不足しているディスクの数が許容範囲の場合は、 7-Mode Transition Tool CLI から次のコマンドを実行して、デグレードアグリゲートを使用して移行を続行できます。

+
`*transition cft aggregate degraded-transition -p _project-name _-n _7-mode-host-name _A_7-mode-aggregate-name _ - 私は * を認めます

+
その後、ケーブル接続の検証処理を再実行して、移行を続行できます。アグリゲートが移行されたあとにこれらの RAID グループを再構築するには、ターゲットクラスタノードに十分な数のスペアディスクを確保する必要があります。

+
この処理に関する重要な考慮事項を示す警告メッセージが表示されます。

. 続行するには、 [ はい ] をクリックします。
+
処理結果が表示されます。

. 処理が完了するまで待ってから、次の手順を実行します。
+
.. [ * CSV として保存 * （ Save as CSV * ） ] をクリックして、操作結果をファイルに保存します。
.. ツールログの収集 * をクリックして、すべての移行ログファイルのバックアップを作成します。
+
移行処理を実行するたびにログファイルを保存することを推奨します。

.. [ 閉じる（ Close ） ] をクリックして、 [ 操作結果（ Operation Results ） ] ウィンドウを閉じる。


+
処理の完了に時間がかかる場合は、 * バックグラウンドで実行 * をクリックすると、処理結果ウィンドウを終了できます。バックグラウンドで処理を実行している間は、プロジェクトを編集したり他のタスクを実行したりしないでください。その後、 [ 操作履歴（ Operation History ） ] タブで操作結果を表示できます。


