---
permalink: snapmirror/reference_7_mode_ontap_version_requirements_for_transitioning_volumes_using_snapmirror.html 
sidebar: sidebar 
keywords: ontap, 7, mode, version, transition, requirements, data, clustered 
summary: 移行を実行する前に、 clustered Data ONTAP 8.3 以降への移行がサポートされる Data ONTAP 7-Mode のバージョンを確認しておく必要があります。 
---
= 移行での 7-Mode のバージョン要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行を実行する前に、 clustered Data ONTAP 8.3 以降への移行がサポートされる Data ONTAP 7-Mode のバージョンを確認しておく必要があります。

7-Mode システムにあるアグリゲートとボリュームがすべて 64 ビットの場合は、次のバージョンの 7-Mode を実行しているシステムからボリュームを clustered Data ONTAP 8.3 以降に移行できます。

* Data ONTAP 8.0 の略
* Data ONTAP 8.0.1 の略
* Data ONTAP 8.0.2
* Data ONTAP 8.0.3 の略
* Data ONTAP 8.0.4
* Data ONTAP 8.0.5 の略
* Data ONTAP 8.1 の略
* Data ONTAP 8.1.2
* Data ONTAP 8.1.3 の場合
* Data ONTAP 8.1.4 の略
* Data ONTAP 8.2 の場合
* Data ONTAP 8.2.1
* Data ONTAP 8.2.2
* Data ONTAP 8.2.3 の略
* Data ONTAP 8.2.4 の略
* Data ONTAP 8.2.5 の略


7-Mode システムで Data ONTAP 8.0.x 、 8.1.x 、または 8.2 を実行していて、 32 ビットのアグリゲートまたはボリュームと 32 ビットの Snapshot コピーがある場合は、 8.1.4 P4 または 8.2.1 にアップグレードする必要があります。アップグレードが完了したら、 32 ビットアグリゲートを 64 ビットに拡張したうえで、 32 ビットデータをすべて削除してください。

次のバージョンの 7-Mode は、 clustered Data ONTAP 8.3 以降に移行する前に、 Data ONTAP 8.1.4 P4 にアップグレードする必要があります。

* Data ONTAP 7.3.3
* Data ONTAP 7.3.4
* Data ONTAP 7.3.5
* Data ONTAP 7.3.6
* Data ONTAP 7.3.7 の略

