---
permalink: snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, volumes, snapmirror, ontap, clustered, data 
summary: clustered Data ONTAP の SnapMirror コマンドを使用すると、 NAS および SAN 環境の 7-Mode ボリュームを clustered Data ONTAP ボリュームに移行できます。移行が完了したら、クラスタ上でプロトコル、サービス、その他の設定を行う必要があります 
---
= SnapMirror を使用して 7-Mode ボリュームを移行する
:icons: font
:imagesdir: ../media/


[role="lead"]
clustered Data ONTAP の SnapMirror コマンドを使用すると、 NAS および SAN 環境の 7-Mode ボリュームを clustered Data ONTAP ボリュームに移行できます。移行が完了したら、クラスタ上でプロトコル、サービス、その他の設定を行う必要があります。

* 推奨事項： * 7-Mode ボリュームを移行する場合は、 7-Mode Transition Tool の使用を推奨します。マイグレーションプロセスのすべてのステップで 7-Mode とクラスタの両方が事前確認で検証されるため、多数の潜在的な問題を回避できます。このツールを使用すると、データ移行だけでなく、すべてのプロトコル、ネットワーク、サービスの設定の移行も大幅に簡易化されます。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-72c-rn/home.html["『 7-Mode Transition Tool Release Notes 』"]

この手順は、 SnapMirror を使用した移行で実行する必要があるタスクの概要を提供します。

. xref:concept_planning_for_transition.adoc[移行予定のボリュームがサポートされていることを確認します 移行の場合]。
. xref:task_preparing_7_mode_system_for_transition.adoc[7-Mode システムで移行を準備]。
. xref:task_preparing_cluster_for_transition.adoc[クラスタで移行を準備]。
. xref:task_creating_a_transition_peering_relationship.adoc[7-Mode システムとの間に、移行ピア関係を作成します ソースと SVM がデスティネーションです]。
. xref:task_transitioning_volumes.adoc[7-Mode ボリュームからクラスタにデータをコピーします Data ONTAP ボリューム：との間に SnapMirror 関係を作成します 2 つのボリューム]。


データの移行が完了したら、次のタスクを実行する必要があります。

* オプション： SVM にデータ LIF を作成してクライアントアクセスを有効にする
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["ネットワークと LIF の管理"]。

* SVM で、プロトコル、ネットワーク、およびサービスを設定します。
+
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["ネットワークと LIF の管理"]。
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["SMB / CIFS の管理"]
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["NFS の管理"]


* igroup を作成して LUN をマッピングします
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["SAN 管理"]

* LUN を含むボリュームを移行する場合は、移行した clustered Data ONTAP ボリュームへのアクセスをリストアする前に、必要な移行後のタスクをホスト上で実行する必要があります。
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-sanspl/home.html["SAN ホストの移行および修復"]



https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]
