---
permalink: snapmirror/task_transitioning_a_stand_alone_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, stand, alone, volume, snapmirror 
summary: スタンドアロンボリュームを移行するには、 SnapMirror 関係を作成し、ベースライン転送を実行し、差分更新を実行し、データコピー処理を監視し、 SnapMirror 関係を解除して、クライアントアクセスを 7-Mode ボリュームから clustered Data ONTAP ボリュームへ移動する必要があります。 
---
= スタンドアロンボリュームの移行
:icons: font
:imagesdir: ../media/


[role="lead"]
スタンドアロンボリュームを移行するには、 SnapMirror 関係を作成し、ベースライン転送を実行し、差分更新を実行し、データコピー処理を監視し、 SnapMirror 関係を解除して、クライアントアクセスを 7-Mode ボリュームから clustered Data ONTAP ボリュームへ移動する必要があります。

* クラスタと SVM のセットアップが完了している必要があります。
* 移行準備に関する情報を確認しておく必要があります。
+
xref:task_preparing_for_transition.adoc[移行を準備しています]



.手順
. 7-Mode ボリュームから clustered Data ONTAP ボリュームへ、データをコピーします。
+
.. 7-Mode システムと SVM の間の SnapMirror 関係に TCP ウィンドウサイズを設定する場合は、「 window-size-for-tdp-mirror 」オプションを使用して「 async-mirror 」タイプの SnapMirror ポリシーを作成します。
+
その後、このポリシーを 7-Mode システムと SVM の間の TDP SnapMirror 関係に適用する必要があります。

+
TCP ウィンドウサイズは 256KB~7MB の範囲で設定でき、 SnapMirror 転送のスループットを向上させて移行時のコピーにかかる時間を短縮できます。TCP ウィンドウサイズのデフォルト値は 2MB です。

+
[listing]
----
cluster1::> snapmirror policy create -vserver vs1 –policy tdp_policy -window-size-for-tdp-mirror 5MB -type async-mirror
----
.. 7-Mode システムと SVM の間に SnapMirror 関係を作成するには、関係タイプを TDP に指定して「 snapmirror create 」コマンドを実行します。
+
TCP ウィンドウサイズを設定するために SnapMirror ポリシーを作成した場合は、この SnapMirror 関係にそのポリシーを適用する必要があります。

+
[listing]
----
cluster1::> snapmirror create -source-path system7mode:dataVol20 -destination-path vs1:dst_vol -type TDP -policy tdp_policy
Operation succeeded: snapmirror create the relationship with destination vs1:dst_vol.
----
.. 「 snapmirror initialize 」コマンドを使用して、ベースライン転送を開始します。
+
[listing]
----
cluster1::> snapmirror initialize -destination-path vs1:dst_vol
Operation is queued: snapmirror initialize of destination vs1:dst_vol.
----
.. 「 snapmirror show 」コマンドを使用して、ステータスを監視します。
+
[listing]
----
cluster1::>snapmirror show -destination-path vs1:dst_vol

                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           **Mirror State: Snapmirrored**
                    Relationship Status: Idle
                File Restore File Count: -
                 File Restore File List: -
                      Transfer Snapshot: -
                      Snapshot Progress: -
                         Total Progress: -
              Network Compression Ratio: -
                    Snapshot Checkpoint: -
                        Newest Snapshot: vs1(4080431166)_dst_vol.1
              Newest Snapshot Timestamp: 10/16 02:49:03
                      Exported Snapshot: vs1(4080431166)_dst_vol.1
            Exported Snapshot Timestamp: 10/16 02:49:03
                                Healthy: true
                       Unhealthy Reason: -
               Constituent Relationship: false
                Destination Volume Node: cluster1-01
                        Relationship ID: 97b205a1-54ff-11e4-9f30-005056a68289
                   Current Operation ID: -
                          Transfer Type: -
                         Transfer Error: -
                       Current Throttle: -
              Current Transfer Priority: -
                     Last Transfer Type: initialize
                    Last Transfer Error: -
                     Last Transfer Size: 152KB
Last Transfer Network Compression Ratio: 1:1
                 Last Transfer Duration: 0:0:6
                     Last Transfer From: system7mode:dataVol20
            Last Transfer End Timestamp: 10/16 02:43:53
                  Progress Last Updated: -
                Relationship Capability: 8.2 and above
                               Lag Time: -
           Number of Successful Updates: 0
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 155648
         Total Transfer Time in Seconds: 6
----
.. clustered Data ONTAP ボリュームを手動で更新するか、 SnapMirror スケジュールを設定して更新するかに応じて、該当する操作を実行します。
+
|===
| 状況 | 作業 


 a| 
転送を手動で更新します
 a| 
... 「 snapmirror update 」コマンドを使用します。
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
----
... 「 snapmirror show 」コマンドを使用して、データコピーのステータスを監視します。
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... 手順 3 に進みます。




 a| 
スケジュールされた更新転送を実行します
 a| 
... 更新転送のスケジュールを作成するには 'job schedule cron create コマンドを使用します
+
[listing]
----
cluster1::> job schedule cron create -name 15_minute_sched -minute 15
----
... 「 snapmirror modify 」コマンドを使用して、 SnapMirror 関係にスケジュールを適用します。
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule 15_minute_sched
----
... 「 snapmirror show 」コマンドを使用して、データコピーのステータスを監視します。
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. 差分転送のスケジュールを設定している場合は、カットオーバーの準備ができた時点で次の手順を実行します。
+
.. 今後のすべての更新転送を無効にするには 'snapmirror quiesce コマンドを使用します
+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs1:dst_vol
----
.. SnapMirror スケジュールを削除するには、「 snapmirror modify 」コマンドを使用します。
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule ""
----
.. SnapMirror 転送を休止していた場合は、「 snapmirror resume 」コマンドを使用して SnapMirror 転送を有効にします。
+
[listing]
----
cluster1::> snapmirror resume -destination-path vs1:dst_vol
----


. 7-Mode ボリュームと clustered Data ONTAP ボリューム間で実行中の転送がある場合はその完了を待ってから、 7-Mode ボリュームからクライアントアクセスを切断してカットオーバーを開始します。
. 「 snapmirror update 」コマンドを使用して、 clustered Data ONTAP ボリュームに対する最終データ更新を実行します。
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
Operation is queued: snapmirror update of destination vs1:dst_vol.
----
. 最後の転送が成功したかどうかを確認するには、「 snapmirror show 」コマンドを使用します。
. 「 snapmirror break 」コマンドを使用して、 7-Mode ボリュームと clustered Data ONTAP ボリュームの間の SnapMirror 関係を解除します。
+
[listing]
----
cluster1::> snapmirror break -destination-path vs1:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. ボリュームに LUN が設定されている場合は、 advanced 権限レベルで、「 lun transition 7-mode show 」コマンドを使用して、 LUN が移行されたことを確認します。
+
clustered Data ONTAP ボリュームで「 lun show 」コマンドを使用して、移行されたすべての LUN を表示することもできます。

. 「 snapmirror delete 」コマンドを使用して、 7-Mode ボリュームと clustered Data ONTAP ボリュームの間の SnapMirror 関係を削除します。
+
[listing]
----
cluster1::> snapmirror delete -destination-path vs1:dst_vol
----
. 「 snapmirror release 」コマンドを使用して、 7-Mode システムから SnapMirror 関係の情報を削除します。
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----


7-Mode システムの必要なボリュームをすべて SVM に移行したら、 7-Mode システムと SVM の間の SVM ピア関係を削除する必要があります。

* 関連情報 *

xref:task_resuming_a_failed_snapmirror_transfer_transition.adoc[失敗した SnapMirror ベースライン転送を再開します]

xref:task_recovering_from_a_failed_lun_transition.adoc[LUN 移行が失敗した場合のリカバリ]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[SnapMirror 関係の TCP ウィンドウサイズの設定]
