---
permalink: snapmirror/task_recovering_from_a_disaster_at_7_mode_site_during_transition.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, snapmirror, recover, disaster, site 
summary: 7-Mode のプライマリボリュームと clustered Data ONTAP のセカンダリボリュームの間に SnapMirror ディザスタリカバリ（ DR ）関係を確立している場合、 7-Mode のプライマリサイトで災害が発生すると、 clustered Data ONTAP のセカンダリボリュームにクライアントアクセスを転送できるようになります。7-Mode のプライマリボリュームがオンラインに復帰したら、追加の手順を実行して、クライアントを clustered Data ONTAP のプライマリボリュームにリダイレクトする必要があります。 
---
= 移行中の 7-Mode サイトでの災害からの復旧
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode のプライマリボリュームと clustered Data ONTAP のセカンダリボリュームの間に SnapMirror ディザスタリカバリ（ DR ）関係が確立されている状況で、 7-Mode のプライマリサイトで災害が発生した場合は、 clustered Data ONTAP のセカンダリボリュームにクライアントアクセスを転送できます。7-Mode のプライマリボリュームがオンラインに復帰したら、追加の手順を実行して、クライアントを clustered Data ONTAP のプライマリボリュームにリダイレクトする必要があります。

clustered Data ONTAP のセカンダリボリュームに書き込まれたデータを災害後も保持するためには、 7-Mode のプライマリボリュームがオンラインに戻ったあとで 7-Mode のプライマリボリュームを移行して、 clustered Data ONTAP のプライマリボリュームとセカンダリボリュームの間に SnapMirror 関係を確立する必要があります。その後、 clustered Data ONTAP のプライマリボリュームへクライアントをリダイレクトします。

clustered Data ONTAP ボリュームから 7-Mode ボリュームへの SnapMirror 再同期はサポートされていません。そのため、災害後に 7-Mode のプライマリボリュームと clustered Data ONTAP のセカンダリボリュームの間に DR 関係を再確立すると、セカンダリ clustered Data ONTAP に書き込まれたデータはすべて失われます。
